# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpl_add_ligand.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(977, 511)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 961, 481))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(330, 40, 91, 141))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tempLig = QtWidgets.QListWidget(self.horizontalLayoutWidget_8)
        self.tempLig.setObjectName("tempLig")
        self.horizontalLayout_8.addWidget(self.tempLig)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(440, 40, 91, 121))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.nTempLig = QtWidgets.QListWidget(self.horizontalLayoutWidget_10)
        self.nTempLig.setObjectName("nTempLig")
        self.horizontalLayout_10.addWidget(self.nTempLig)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(440, 160, 91, 21))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.nTempLigCount = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.nTempLigCount.setObjectName("nTempLigCount")
        self.horizontalLayout_11.addWidget(self.nTempLigCount)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(440, 21, 91, 20))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(330, 21, 91, 20))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(220, 21, 91, 20))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(220, 40, 91, 141))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stdRes = QtWidgets.QListWidget(self.horizontalLayoutWidget_5)
        self.stdRes.setObjectName("stdRes")
        self.horizontalLayout_5.addWidget(self.stdRes)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(780, 30, 171, 151))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ligandAdded = QtWidgets.QListWidget(self.horizontalLayoutWidget_17)
        self.ligandAdded.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ligandAdded.setObjectName("ligandAdded")
        self.horizontalLayout_17.addWidget(self.ligandAdded)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(720, 29, 51, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.addLigBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addLigBut.setObjectName("addLigBut")
        self.verticalLayout.addWidget(self.addLigBut)
        self.minLigBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.minLigBut.setObjectName("minLigBut")
        self.verticalLayout.addWidget(self.minLigBut)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.group_restraint = QtWidgets.QGroupBox(self.groupBox_2)
        self.group_restraint.setGeometry(QtCore.QRect(0, 210, 961, 221))
        self.group_restraint.setFlat(True)
        self.group_restraint.setObjectName("group_restraint")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.group_restraint)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 60, 1100, 31))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.layout_mathForm = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.layout_mathForm.setContentsMargins(0, 0, 0, 0)
        self.layout_mathForm.setObjectName("layout_mathForm")
        self.cosinePeriodLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.cosinePeriodLabel.setObjectName("cosinePeriodLabel")
        self.layout_mathForm.addWidget(self.cosinePeriodLabel, 0, 22, 1, 1)
        self.len_jonsParamBLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.len_jonsParamBLabel.setObjectName("len_jonsParamBLabel")
        self.layout_mathForm.addWidget(self.len_jonsParamBLabel, 0, 12, 1, 1)
        self.weights = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.weights.setObjectName("weights")
        self.layout_mathForm.addWidget(self.weights, 0, 9, 1, 1)
        self.coulombQ1 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.coulombQ1.setObjectName("coulombQ1")
        self.layout_mathForm.addWidget(self.coulombQ1, 0, 15, 1, 1)
        self.cosineForce = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.cosineForce.setObjectName("cosineForce")
        self.layout_mathForm.addWidget(self.cosineForce, 0, 21, 1, 1)
        self.len_jonsParamB = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.len_jonsParamB.setObjectName("len_jonsParamB")
        self.layout_mathForm.addWidget(self.len_jonsParamB, 0, 13, 1, 1)
        self.coulombQ2Label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.coulombQ2Label.setObjectName("coulombQ2Label")
        self.layout_mathForm.addWidget(self.coulombQ2Label, 0, 16, 1, 1)
        self.cosineForceLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.cosineForceLabel.setObjectName("cosineForceLabel")
        self.layout_mathForm.addWidget(self.cosineForceLabel, 0, 20, 1, 1)
        self.coulombQ2 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.coulombQ2.setObjectName("coulombQ2")
        self.layout_mathForm.addWidget(self.coulombQ2, 0, 17, 1, 1)
        self.weightsLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.weightsLabel.setObjectName("weightsLabel")
        self.layout_mathForm.addWidget(self.weightsLabel, 0, 8, 1, 1)
        self.len_jonsParamA = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.len_jonsParamA.setObjectName("len_jonsParamA")
        self.layout_mathForm.addWidget(self.len_jonsParamA, 0, 11, 1, 1)
        self.cosinePhaseLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.cosinePhaseLabel.setObjectName("cosinePhaseLabel")
        self.layout_mathForm.addWidget(self.cosinePhaseLabel, 0, 18, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_26.setObjectName("label_26")
        self.layout_mathForm.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_27.setObjectName("label_27")
        self.layout_mathForm.addWidget(self.label_27, 0, 2, 1, 1)
        self.matForm = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.matForm.setObjectName("matForm")
        self.layout_mathForm.addWidget(self.matForm, 0, 1, 1, 1)
        self.meanLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.meanLabel.setObjectName("meanLabel")
        self.layout_mathForm.addWidget(self.meanLabel, 0, 4, 1, 1)
        self.mean = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.mean.setObjectName("mean")
        self.layout_mathForm.addWidget(self.mean, 0, 5, 1, 1)
        self.physicalFeat = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.physicalFeat.setObjectName("physicalFeat")
        self.layout_mathForm.addWidget(self.physicalFeat, 0, 3, 1, 1)
        self.stdev = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.stdev.setObjectName("stdev")
        self.layout_mathForm.addWidget(self.stdev, 0, 7, 1, 1)
        self.stdevLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.stdevLabel.setObjectName("stdevLabel")
        self.layout_mathForm.addWidget(self.stdevLabel, 0, 6, 1, 1)
        self.len_jonsParamALabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.len_jonsParamALabel.setObjectName("len_jonsParamALabel")
        self.layout_mathForm.addWidget(self.len_jonsParamALabel, 0, 10, 1, 1)
        self.cosinePhase = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.cosinePhase.setObjectName("cosinePhase")
        self.layout_mathForm.addWidget(self.cosinePhase, 0, 19, 1, 1)
        self.coulombQ1Label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.coulombQ1Label.setObjectName("coulombQ1Label")
        self.layout_mathForm.addWidget(self.coulombQ1Label, 0, 14, 1, 1)
        self.cosinePeriod = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.cosinePeriod.setObjectName("cosinePeriod")
        self.layout_mathForm.addWidget(self.cosinePeriod, 0, 23, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.group_restraint)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 916, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.layout_atmFeature = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.layout_atmFeature.setContentsMargins(0, 0, 0, 0)
        self.layout_atmFeature.setObjectName("layout_atmFeature")
        self.atm1Check = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.atm1Check.setText("")
        self.atm1Check.setObjectName("atm1Check")
        self.layout_atmFeature.addWidget(self.atm1Check, 0, 6, 1, 1)
        self.atm1Namefrom = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.atm1Namefrom.setObjectName("atm1Namefrom")
        self.layout_atmFeature.addWidget(self.atm1Namefrom, 0, 3, 1, 1)
        self.atm1Chain = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.atm1Chain.setObjectName("atm1Chain")
        self.layout_atmFeature.addWidget(self.atm1Chain, 0, 5, 1, 1)
        self.atm1Numfrom = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.atm1Numfrom.setObjectName("atm1Numfrom")
        self.layout_atmFeature.addWidget(self.atm1Numfrom, 0, 4, 1, 1)
        self.atmFeatures = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.atmFeatures.setObjectName("atmFeatures")
        self.layout_atmFeature.addWidget(self.atmFeatures, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.layout_atmFeature.addWidget(self.label_21, 0, 0, 1, 1)
        self.atm2NumTo = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.atm2NumTo.setObjectName("atm2NumTo")
        self.layout_atmFeature.addWidget(self.atm2NumTo, 0, 9, 1, 1)
        self.atm2NameTo = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.atm2NameTo.setObjectName("atm2NameTo")
        self.layout_atmFeature.addWidget(self.atm2NameTo, 0, 8, 1, 1)
        self.labelAfterFeat = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelAfterFeat.setObjectName("labelAfterFeat")
        self.layout_atmFeature.addWidget(self.labelAfterFeat, 0, 2, 1, 1)
        self.atmAndLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.atmAndLabel.setObjectName("atmAndLabel")
        self.layout_atmFeature.addWidget(self.atmAndLabel, 0, 7, 1, 1)
        self.atm3Check = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.atm3Check.setText("")
        self.atm3Check.setObjectName("atm3Check")
        self.layout_atmFeature.addWidget(self.atm3Check, 0, 16, 1, 1)
        self.atm2Chain = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.atm2Chain.setObjectName("atm2Chain")
        self.layout_atmFeature.addWidget(self.atm2Chain, 0, 10, 1, 1)
        self.atm2Check = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.atm2Check.setText("")
        self.atm2Check.setObjectName("atm2Check")
        self.layout_atmFeature.addWidget(self.atm2Check, 0, 11, 1, 1)
        self.atm3NumTo = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.atm3NumTo.setObjectName("atm3NumTo")
        self.layout_atmFeature.addWidget(self.atm3NumTo, 0, 14, 1, 1)
        self.atm3Chain = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.atm3Chain.setObjectName("atm3Chain")
        self.layout_atmFeature.addWidget(self.atm3Chain, 0, 15, 1, 1)
        self.atm3AndLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.atm3AndLabel.setObjectName("atm3AndLabel")
        self.layout_atmFeature.addWidget(self.atm3AndLabel, 0, 12, 1, 1)
        self.atm3NameTo = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.atm3NameTo.setObjectName("atm3NameTo")
        self.layout_atmFeature.addWidget(self.atm3NameTo, 0, 13, 1, 1)
        self.atm4AndLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.atm4AndLabel.setObjectName("atm4AndLabel")
        self.layout_atmFeature.addWidget(self.atm4AndLabel, 0, 17, 1, 1)
        self.atm4NameTo = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.atm4NameTo.setObjectName("atm4NameTo")
        self.layout_atmFeature.addWidget(self.atm4NameTo, 0, 18, 1, 1)
        self.atm4Chain = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.atm4Chain.setObjectName("atm4Chain")
        self.layout_atmFeature.addWidget(self.atm4Chain, 0, 20, 1, 1)
        self.atm4NumTo = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.atm4NumTo.setObjectName("atm4NumTo")
        self.layout_atmFeature.addWidget(self.atm4NumTo, 0, 19, 1, 1)
        self.atm4Check = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.atm4Check.setText("")
        self.atm4Check.setObjectName("atm4Check")
        self.layout_atmFeature.addWidget(self.atm4Check, 0, 21, 1, 1)
        self.horizontalLayoutWidget_30 = QtWidgets.QWidget(self.group_restraint)
        self.horizontalLayoutWidget_30.setGeometry(QtCore.QRect(9, 109, 941, 111))
        self.horizontalLayoutWidget_30.setObjectName("horizontalLayoutWidget_30")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_30)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.atmFeatMat = QtWidgets.QListWidget(self.horizontalLayoutWidget_30)
        self.atmFeatMat.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.atmFeatMat.setObjectName("atmFeatMat")
        self.horizontalLayout_33.addWidget(self.atmFeatMat)
        self.horizontalLayoutWidget_31 = QtWidgets.QWidget(self.group_restraint)
        self.horizontalLayoutWidget_31.setGeometry(QtCore.QRect(570, 60, 131, 31))
        self.horizontalLayoutWidget_31.setObjectName("horizontalLayoutWidget_31")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_31)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.addFeature_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_31)
        self.addFeature_2.setObjectName("addFeature_2")
        self.horizontalLayout_37.addWidget(self.addFeature_2)
        self.minFeature_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_31)
        self.minFeature_2.setObjectName("minFeature_2")
        self.horizontalLayout_37.addWidget(self.minFeature_2)
        self.horizontalLayoutWidget_32 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_32.setGeometry(QtCore.QRect(0, 450, 951, 31))
        self.horizontalLayoutWidget_32.setObjectName("horizontalLayoutWidget_32")
        self.layout_apply = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_32)
        self.layout_apply.setContentsMargins(0, 0, 0, 0)
        self.layout_apply.setObjectName("layout_apply")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_apply.addItem(spacerItem2)
        self.applyBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_32)
        self.applyBut.setObjectName("applyBut")
        self.layout_apply.addWidget(self.applyBut)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_apply.addItem(spacerItem3)
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(0, 432, 951, 31))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.msgLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        self.msgLabel.setText("")
        self.msgLabel.setObjectName("msgLabel")
        self.horizontalLayout_19.addWidget(self.msgLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(550, 30, 161, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.restraint = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.restraint.setObjectName("restraint")
        self.gridLayout.addWidget(self.restraint, 0, 1, 1, 1)
        self.seqId = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.seqId.setObjectName("seqId")
        self.gridLayout.addWidget(self.seqId, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.addChainIdent = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.addChainIdent.setObjectName("addChainIdent")
        self.gridLayout.addWidget(self.addChainIdent, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 191, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.alignFile = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.alignFile.setObjectName("alignFile")
        self.gridLayout_2.addWidget(self.alignFile, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.templates = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.templates.setObjectName("templates")
        self.gridLayout_2.addWidget(self.templates, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Add Ligand"))
        self.nTempLigCount.setPlaceholderText(_translate("Form", "Count"))
        self.label_5.setText(_translate("Form", "Non-template ligands"))
        self.label_4.setText(_translate("Form", "Template ligands"))
        self.label_3.setText(_translate("Form", "Standard residues"))
        self.addLigBut.setText(_translate("Form", "Add"))
        self.minLigBut.setText(_translate("Form", "Delete"))
        self.group_restraint.setTitle(_translate("Form", "Define Restraint"))
        self.cosinePeriodLabel.setText(_translate("Form", "period:"))
        self.len_jonsParamBLabel.setText(_translate("Form", "parameter B:"))
        self.coulombQ2Label.setText(_translate("Form", "charge Q2:"))
        self.cosineForceLabel.setText(_translate("Form", "force:"))
        self.weightsLabel.setText(_translate("Form", "weights:"))
        self.cosinePhaseLabel.setText(_translate("Form", "phase:"))
        self.label_26.setText(_translate("Form", "in form:"))
        self.label_27.setText(_translate("Form", "for feature:"))
        self.meanLabel.setText(_translate("Form", "mean:"))
        self.stdevLabel.setText(_translate("Form", "STDEV:"))
        self.len_jonsParamALabel.setText(_translate("Form", "parameter A:"))
        self.coulombQ1Label.setText(_translate("Form", "charge Q1:"))
        self.label_21.setText(_translate("Form", "Add:"))
        self.labelAfterFeat.setText(_translate("Form", "in Å between:"))
        self.atmAndLabel.setText(_translate("Form", "  &  "))
        self.atm3AndLabel.setText(_translate("Form", "  &  "))
        self.atm4AndLabel.setText(_translate("Form", "  &  "))
        self.addFeature_2.setText(_translate("Form", "Add"))
        self.minFeature_2.setText(_translate("Form", "Delete"))
        self.applyBut.setText(_translate("Form", "Apply"))
        self.label_6.setText(_translate("Form", "Restraint:"))
        self.label_7.setText(_translate("Form", "Sequence ID:"))
        self.addChainIdent.setText(_translate("Form", "Use different chain id"))
        self.label.setText(_translate("Form", "Alignment file:"))
        self.label_2.setText(_translate("Form", "Templates:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
