# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpl_build_model.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(972, 502)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 961, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 249, 961, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.downLibBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.downLibBut.setObjectName("downLibBut")
        self.horizontalLayout_11.addWidget(self.downLibBut)
        self.buildBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.buildBut.setObjectName("buildBut")
        self.horizontalLayout_11.addWidget(self.buildBut)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 232, 961, 22))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.msgLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.msgLabel.setText("")
        self.msgLabel.setObjectName("msgLabel")
        self.horizontalLayout_12.addWidget(self.msgLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.frame_addMinChain = QtWidgets.QFrame(self.groupBox)
        self.frame_addMinChain.setEnabled(False)
        self.frame_addMinChain.setGeometry(QtCore.QRect(570, 170, 121, 31))
        self.frame_addMinChain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_addMinChain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_addMinChain.setObjectName("frame_addMinChain")
        self.frame_sym = QtWidgets.QFrame(self.groupBox)
        self.frame_sym.setEnabled(True)
        self.frame_sym.setGeometry(QtCore.QRect(710, 20, 241, 171))
        self.frame_sym.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sym.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sym.setObjectName("frame_sym")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.frame_sym)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 241, 171))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.symAdded = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.symAdded.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.symAdded.setObjectName("symAdded")
        self.gridLayout_4.addWidget(self.symAdded, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.addsym_residue_atomBut = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.addsym_residue_atomBut.setObjectName("addsym_residue_atomBut")
        self.horizontalLayout_7.addWidget(self.addsym_residue_atomBut)
        self.minsym_residue_atomBut = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.minsym_residue_atomBut.setObjectName("minsym_residue_atomBut")
        self.horizontalLayout_7.addWidget(self.minsym_residue_atomBut)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.atmFrom = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.atmFrom.setEditable(True)
        self.atmFrom.setObjectName("atmFrom")
        self.horizontalLayout_6.addWidget(self.atmFrom)
        self.chainFrom = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.chainFrom.setEditable(True)
        self.chainFrom.setObjectName("chainFrom")
        self.horizontalLayout_6.addWidget(self.chainFrom)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.atmTo = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.atmTo.setEditable(True)
        self.atmTo.setObjectName("atmTo")
        self.horizontalLayout_6.addWidget(self.atmTo)
        self.chainTo = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.chainTo.setEditable(True)
        self.chainTo.setObjectName("chainTo")
        self.horizontalLayout_6.addWidget(self.chainTo)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.symDevLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.symDevLabel.setEnabled(True)
        self.symDevLabel.setObjectName("symDevLabel")
        self.gridLayout_4.addWidget(self.symDevLabel, 3, 0, 1, 1)
        self.symDev = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.symDev.setEnabled(True)
        self.symDev.setObjectName("symDev")
        self.gridLayout_4.addWidget(self.symDev, 3, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 231, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.alignFile = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.alignFile.setObjectName("alignFile")
        self.gridLayout.addWidget(self.alignFile, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.templates = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.templates.setObjectName("templates")
        self.gridLayout.addWidget(self.templates, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.seqId = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.seqId.setObjectName("seqId")
        self.gridLayout.addWidget(self.seqId, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(260, 20, 201, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.restraint = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.restraint.setObjectName("restraint")
        self.gridLayout_2.addWidget(self.restraint, 0, 1, 1, 1)
        self.assess = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.assess.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.assess.setObjectName("assess")
        self.gridLayout_2.addWidget(self.assess, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.deviation = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.deviation.setObjectName("deviation")
        self.gridLayout_2.addWidget(self.deviation, 2, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(480, 20, 215, 194))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chains = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.chains.setEnabled(False)
        self.chains.setObjectName("chains")
        self.gridLayout_3.addWidget(self.chains, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.mChAlignWith = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.mChAlignWith.setEnabled(False)
        self.mChAlignWith.setObjectName("mChAlignWith")
        self.gridLayout_3.addWidget(self.mChAlignWith, 4, 1, 1, 1)
        self.mChAlignWithLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.mChAlignWithLabel.setEnabled(False)
        self.mChAlignWithLabel.setObjectName("mChAlignWithLabel")
        self.gridLayout_3.addWidget(self.mChAlignWithLabel, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.chainsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.chainsLabel.setEnabled(False)
        self.chainsLabel.setObjectName("chainsLabel")
        self.gridLayout_3.addWidget(self.chainsLabel, 5, 0, 1, 1)
        self.multiChain = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.multiChain.setObjectName("multiChain")
        self.gridLayout_3.addWidget(self.multiChain, 2, 1, 1, 1)
        self.useSymmetry = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.useSymmetry.setObjectName("useSymmetry")
        self.gridLayout_3.addWidget(self.useSymmetry, 3, 1, 1, 1)
        self.vtfm = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.vtfm.setObjectName("vtfm")
        self.gridLayout_3.addWidget(self.vtfm, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.addHydrogen = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.addHydrogen.setObjectName("addHydrogen")
        self.gridLayout_3.addWidget(self.addHydrogen, 1, 1, 1, 1)
        self.layout_addMinChain = QtWidgets.QHBoxLayout()
        self.layout_addMinChain.setObjectName("layout_addMinChain")
        self.addchaintofileBut = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.addchaintofileBut.setObjectName("addchaintofileBut")
        self.layout_addMinChain.addWidget(self.addchaintofileBut)
        self.minchainfromfileBut = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.minchainfromfileBut.setObjectName("minchainfromfileBut")
        self.layout_addMinChain.addWidget(self.minchainfromfileBut)
        self.gridLayout_3.addLayout(self.layout_addMinChain, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.msgLabel_chain = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.msgLabel_chain.setText("")
        self.msgLabel_chain.setObjectName("msgLabel_chain")
        self.horizontalLayout_5.addWidget(self.msgLabel_chain)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 7, 1, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(710, 190, 241, 31))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.numModel = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numModel.sizePolicy().hasHeightForWidth())
        self.numModel.setSizePolicy(sizePolicy)
        self.numModel.setObjectName("numModel")
        self.gridLayout_5.addWidget(self.numModel, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 300, 961, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group_model_result = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.group_model_result.setObjectName("group_model_result")
        self.table_model_result = QtWidgets.QTableView(self.group_model_result)
        self.table_model_result.setGeometry(QtCore.QRect(10, 20, 941, 121))
        self.table_model_result.setShowGrid(False)
        self.table_model_result.setSortingEnabled(True)
        self.table_model_result.setObjectName("table_model_result")
        self.horizontalLayoutWidget_34 = QtWidgets.QWidget(self.group_model_result)
        self.horizontalLayoutWidget_34.setGeometry(QtCore.QRect(0, 161, 951, 31))
        self.horizontalLayoutWidget_34.setObjectName("horizontalLayoutWidget_34")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_34)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem6)
        self.saveCsvBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_34)
        self.saveCsvBut.setObjectName("saveCsvBut")
        self.horizontalLayout_36.addWidget(self.saveCsvBut)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem7)
        self.horizontalLayoutWidget_35 = QtWidgets.QWidget(self.group_model_result)
        self.horizontalLayoutWidget_35.setGeometry(QtCore.QRect(0, 150, 951, 22))
        self.horizontalLayoutWidget_35.setObjectName("horizontalLayoutWidget_35")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_35)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem8)
        self.msglabel_csv = QtWidgets.QLabel(self.horizontalLayoutWidget_35)
        self.msglabel_csv.setText("")
        self.msglabel_csv.setObjectName("msglabel_csv")
        self.horizontalLayout_37.addWidget(self.msglabel_csv)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem9)
        self.verticalLayout_2.addWidget(self.group_model_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Build Model"))
        self.downLibBut.setText(_translate("Form", "Download library"))
        self.buildBut.setText(_translate("Form", "Build"))
        self.label_12.setText(_translate("Form", "Atom type:"))
        self.addsym_residue_atomBut.setText(_translate("Form", "Add"))
        self.minsym_residue_atomBut.setText(_translate("Form", "Delete"))
        self.label_13.setText(_translate("Form", "&"))
        self.symDevLabel.setToolTip(_translate("Form", "Symmetry deviation"))
        self.symDevLabel.setText(_translate("Form", "Sym dev:"))
        self.label.setText(_translate("Form", "Alignment file:"))
        self.label_2.setText(_translate("Form", "Templates:"))
        self.label_14.setText(_translate("Form", "Sequence ID:"))
        self.label_6.setToolTip(_translate("Form", "<html><head/><body><p>By default GA341, DOPE, DOPE-HR and Normalized DOPE score libraries are included in MODELLER installatine file. To use SOAP librarise download corresponding files from: </p></body></html>"))
        self.label_6.setText(_translate("Form", "Assess method:"))
        self.label_5.setText(_translate("Form", "Restraint file:"))
        self.label_3.setToolTip(_translate("Form", "<html><head/><body><p>Controls the amount of randomization which randomize all coordinates (X, Y, Z) of standard residues.</p></body></html>"))
        self.label_3.setText(_translate("Form", "Deviation:"))
        self.label_8.setText(_translate("Form", "Add hydrogen:"))
        self.mChAlignWithLabel.setText(_translate("Form", "Align with:"))
        self.label_9.setText(_translate("Form", "Multi chain model:"))
        self.chainsLabel.setText(_translate("Form", "Chains:"))
        self.label_10.setText(_translate("Form", "Use symmetry:"))
        self.addchaintofileBut.setText(_translate("Form", "Add"))
        self.minchainfromfileBut.setText(_translate("Form", "Remove"))
        self.label_4.setToolTip(_translate("Form", "<html><head/><body><p>Each model is first optimized with the variable target function method (VTFM) with conjugate gradients (CG), and is then refined using molecular dynamics (MD) with simulated annealing (SA).</p></body></html>"))
        self.label_4.setText(_translate("Form", "VTFM optimization:"))
        self.label_16.setText(_translate("Form", "# Models: "))
        self.group_model_result.setTitle(_translate("Form", "Results"))
        self.saveCsvBut.setText(_translate("Form", "Save as CSV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

