# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpl_evaluate_model.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(978, 593)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 961, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(510, 42, 61, 21))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.addButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 0, 0, 1, 1)
        self.minButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minButton.setObjectName("minButton")
        self.gridLayout.addWidget(self.minButton, 0, 1, 1, 1)
        self.horizontalLayoutWidget_24 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_24.setGeometry(QtCore.QRect(0, 170, 961, 31))
        self.horizontalLayoutWidget_24.setObjectName("horizontalLayoutWidget_24")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_24)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem)
        self.evalBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_24)
        self.evalBut.setObjectName("evalBut")
        self.horizontalLayout_24.addWidget(self.evalBut)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.horizontalLayoutWidget_25 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_25.setGeometry(QtCore.QRect(0, 160, 961, 22))
        self.horizontalLayoutWidget_25.setObjectName("horizontalLayoutWidget_25")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_25)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem2)
        self.msg = QtWidgets.QLabel(self.horizontalLayoutWidget_25)
        self.msg.setText("")
        self.msg.setObjectName("msg")
        self.horizontalLayout_25.addWidget(self.msg)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem3)
        self.horizontalLayoutWidget_26 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_26.setGeometry(QtCore.QRect(510, 20, 61, 21))
        self.horizontalLayoutWidget_26.setObjectName("horizontalLayoutWidget_26")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_26)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.pickColor = QtWidgets.QPushButton(self.horizontalLayoutWidget_26)
        self.pickColor.setObjectName("pickColor")
        self.horizontalLayout_26.addWidget(self.pickColor)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 261, 101))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.alignFile = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.alignFile.setObjectName("alignFile")
        self.gridLayout_6.addWidget(self.alignFile, 1, 1, 1, 1)
        self.model = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.model.setObjectName("model")
        self.gridLayout_6.addWidget(self.model, 0, 1, 1, 1)
        self.assess = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.assess.setObjectName("assess")
        self.gridLayout_6.addWidget(self.assess, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 3, 0, 1, 1)
        self.modelId = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.modelId.setObjectName("modelId")
        self.gridLayout_6.addWidget(self.modelId, 3, 1, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(290, 20, 211, 131))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.tempColorEntry = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.tempColorEntry.setObjectName("tempColorEntry")
        self.gridLayout_7.addWidget(self.tempColorEntry, 1, 1, 1, 1)
        self.template_2 = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.template_2.setObjectName("template_2")
        self.gridLayout_7.addWidget(self.template_2, 0, 1, 1, 1)
        self.tempColor = QtWidgets.QListWidget(self.gridLayoutWidget_7)
        self.tempColor.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tempColor.setObjectName("tempColor")
        self.gridLayout_7.addWidget(self.tempColor, 2, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(600, 20, 231, 131))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineWidth = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineWidth.setObjectName("lineWidth")
        self.gridLayout_8.addWidget(self.lineWidth, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.figSizeY = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.figSizeY.setObjectName("figSizeY")
        self.gridLayout_2.addWidget(self.figSizeY, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.figSizeX = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.figSizeX.setObjectName("figSizeX")
        self.gridLayout_2.addWidget(self.figSizeX, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 4, 0, 1, 1)
        self.xlabel = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.xlabel.setObjectName("xlabel")
        self.gridLayout_8.addWidget(self.xlabel, 2, 1, 1, 1)
        self.ylabel = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.ylabel.setObjectName("ylabel")
        self.gridLayout_8.addWidget(self.ylabel, 3, 1, 1, 1)
        self.energy_save_as = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.energy_save_as.setObjectName("energy_save_as")
        self.gridLayout_8.addWidget(self.energy_save_as, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 380, 961, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group_outlier = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.group_outlier.setObjectName("group_outlier")
        self.table_results = QtWidgets.QTableView(self.group_outlier)
        self.table_results.setGeometry(QtCore.QRect(10, 50, 941, 111))
        self.table_results.setAutoFillBackground(False)
        self.table_results.setShowGrid(False)
        self.table_results.setSortingEnabled(True)
        self.table_results.setObjectName("table_results")
        self.horizontalLayoutWidget_35 = QtWidgets.QWidget(self.group_outlier)
        self.horizontalLayoutWidget_35.setGeometry(QtCore.QRect(0, 180, 971, 22))
        self.horizontalLayoutWidget_35.setObjectName("horizontalLayoutWidget_35")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_35)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem4)
        self.saveCsvBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_35)
        self.saveCsvBut.setObjectName("saveCsvBut")
        self.horizontalLayout_36.addWidget(self.saveCsvBut)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem5)
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.group_outlier)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(10, 20, 161, 21))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 0, 1, 1)
        self.display_outlier = QtWidgets.QComboBox(self.gridLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_outlier.sizePolicy().hasHeightForWidth())
        self.display_outlier.setSizePolicy(sizePolicy)
        self.display_outlier.setObjectName("display_outlier")
        self.gridLayout_11.addWidget(self.display_outlier, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.group_outlier)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(180, 20, 71, 21))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.outlier_count_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.outlier_count_label.setText("")
        self.outlier_count_label.setObjectName("outlier_count_label")
        self.gridLayout_12.addWidget(self.outlier_count_label, 0, 0, 1, 1)
        self.horizontalLayoutWidget_40 = QtWidgets.QWidget(self.group_outlier)
        self.horizontalLayoutWidget_40.setGeometry(QtCore.QRect(0, 161, 961, 22))
        self.horizontalLayoutWidget_40.setObjectName("horizontalLayoutWidget_40")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_40)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem6)
        self.msglabel_csv = QtWidgets.QLabel(self.horizontalLayoutWidget_40)
        self.msglabel_csv.setText("")
        self.msglabel_csv.setObjectName("msglabel_csv")
        self.horizontalLayout_40.addWidget(self.msglabel_csv)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem7)
        self.verticalLayout_2.addWidget(self.group_outlier)
        self.horizontalLayoutWidget_37 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_37.setGeometry(QtCore.QRect(10, 220, 961, 151))
        self.horizontalLayoutWidget_37.setObjectName("horizontalLayoutWidget_37")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_37)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_37)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(260, 20, 256, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.rama_prePro = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.rama_prePro.setChecked(True)
        self.rama_prePro.setObjectName("rama_prePro")
        self.gridLayout_3.addWidget(self.rama_prePro, 0, 4, 1, 1)
        self.rama_gen = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.rama_gen.setChecked(True)
        self.rama_gen.setTristate(False)
        self.rama_gen.setObjectName("rama_gen")
        self.gridLayout_3.addWidget(self.rama_gen, 0, 1, 1, 1)
        self.rama_gly = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.rama_gly.setChecked(True)
        self.rama_gly.setObjectName("rama_gly")
        self.gridLayout_3.addWidget(self.rama_gly, 0, 2, 1, 1)
        self.rama_pro = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.rama_pro.setChecked(True)
        self.rama_pro.setObjectName("rama_pro")
        self.gridLayout_3.addWidget(self.rama_pro, 0, 3, 1, 1)
        self.horizontalLayoutWidget_39 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_39.setGeometry(QtCore.QRect(0, 108, 961, 22))
        self.horizontalLayoutWidget_39.setObjectName("horizontalLayoutWidget_39")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_39)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem8)
        self.msglabel_rama = QtWidgets.QLabel(self.horizontalLayoutWidget_39)
        self.msglabel_rama.setText("")
        self.msglabel_rama.setObjectName("msglabel_rama")
        self.horizontalLayout_39.addWidget(self.msglabel_rama)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem9)
        self.horizontalLayoutWidget_38 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_38.setGeometry(QtCore.QRect(0, 120, 961, 31))
        self.horizontalLayoutWidget_38.setObjectName("horizontalLayoutWidget_38")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_38)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem10)
        self.evalRamaBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_38)
        self.evalRamaBut.setObjectName("evalRamaBut")
        self.horizontalLayout_38.addWidget(self.evalRamaBut)
        self.removeBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_38)
        self.removeBut.setObjectName("removeBut")
        self.horizontalLayout_38.addWidget(self.removeBut)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem11)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 231, 91))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 0, 0, 1, 1)
        self.rama_pdb = QtWidgets.QListWidget(self.gridLayoutWidget_9)
        self.rama_pdb.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.rama_pdb.setObjectName("rama_pdb")
        self.gridLayout_9.addWidget(self.rama_pdb, 0, 1, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(260, 50, 251, 37))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.annot = QtWidgets.QComboBox(self.formLayoutWidget)
        self.annot.setObjectName("annot")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.annot)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(530, 20, 231, 51))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.rama_save_as = QtWidgets.QComboBox(self.gridLayoutWidget_10)
        self.rama_save_as.setObjectName("rama_save_as")
        self.gridLayout_10.addWidget(self.rama_save_as, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.figSizeX_rama = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.figSizeX_rama.setObjectName("figSizeX_rama")
        self.gridLayout_4.addWidget(self.figSizeX_rama, 0, 0, 1, 1)
        self.figSizeY_rama = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.figSizeY_rama.setObjectName("figSizeY_rama")
        self.gridLayout_4.addWidget(self.figSizeY_rama, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 0, 1, 1)
        self.horizontalLayout_35.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Evaluate Energy Levels"))
        self.addButton.setText(_translate("Form", "+"))
        self.minButton.setText(_translate("Form", "-"))
        self.evalBut.setText(_translate("Form", "Evaluate"))
        self.pickColor.setText(_translate("Form", "Color"))
        self.label.setText(_translate("Form", "Model:"))
        self.label_3.setText(_translate("Form", "Assess method:"))
        self.label_2.setText(_translate("Form", "Alignment file:"))
        self.label_5.setText(_translate("Form", "Model id:"))
        self.label_6.setText(_translate("Form", "Template:"))
        self.label_12.setText(_translate("Form", "Y label:"))
        self.label_11.setText(_translate("Form", "X label:"))
        self.label_10.setText(_translate("Form", "Line width:"))
        self.label_9.setText(_translate("Form", "X"))
        self.label_8.setText(_translate("Form", "Figure size:"))
        self.label_17.setText(_translate("Form", "Save as:"))
        self.group_outlier.setTitle(_translate("Form", "Outliers"))
        self.saveCsvBut.setText(_translate("Form", "Save as CSV"))
        self.label_4.setText(_translate("Form", "Display:"))
        self.groupBox_2.setTitle(_translate("Form", "Evaluate Phi and Psi Angles"))
        self.label_13.setText(_translate("Form", "Type:"))
        self.rama_prePro.setText(_translate("Form", "Pre-Proline"))
        self.rama_gen.setText(_translate("Form", "General"))
        self.rama_gly.setText(_translate("Form", "Glycine"))
        self.rama_pro.setText(_translate("Form", "Proline"))
        self.evalRamaBut.setText(_translate("Form", "Evaluate"))
        self.removeBut.setText(_translate("Form", "Remove"))
        self.label_14.setText(_translate("Form", "Model:"))
        self.label_15.setText(_translate("Form", "Outlier label:"))
        self.label_16.setText(_translate("Form", "Save as:"))
        self.label_19.setText(_translate("Form", "X"))
        self.label_18.setText(_translate("Form", "Figure size:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

