# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpl_optimize_model.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(978, 491)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 961, 231))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_59 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_59.setGeometry(QtCore.QRect(0, 200, 961, 31))
        self.horizontalLayoutWidget_59.setObjectName("horizontalLayoutWidget_59")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_59)
        self.horizontalLayout_59.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem)
        self.optBackBoneBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_59)
        self.optBackBoneBut.setObjectName("optBackBoneBut")
        self.horizontalLayout_59.addWidget(self.optBackBoneBut)
        self.backBone_remove = QtWidgets.QPushButton(self.horizontalLayoutWidget_59)
        self.backBone_remove.setObjectName("backBone_remove")
        self.horizontalLayout_59.addWidget(self.backBone_remove)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem1)
        self.horizontalLayoutWidget_81 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_81.setGeometry(QtCore.QRect(0, 180, 961, 31))
        self.horizontalLayoutWidget_81.setObjectName("horizontalLayoutWidget_81")
        self.horizontalLayout_91 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_81)
        self.horizontalLayout_91.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_91.setObjectName("horizontalLayout_91")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_91.addItem(spacerItem2)
        self.msg_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_81)
        self.msg_1.setText("")
        self.msg_1.setObjectName("msg_1")
        self.horizontalLayout_91.addWidget(self.msg_1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_91.addItem(spacerItem3)
        self.gridLayoutWidget_40 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_40.setGeometry(QtCore.QRect(10, 20, 311, 151))
        self.gridLayoutWidget_40.setObjectName("gridLayoutWidget_40")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_40)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_40)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 0, 0, 1, 1)
        self.optimizeMethod = QtWidgets.QComboBox(self.gridLayoutWidget_40)
        self.optimizeMethod.setObjectName("optimizeMethod")
        self.gridLayout_12.addWidget(self.optimizeMethod, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_40)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 1, 0, 1, 1)
        self.model = QtWidgets.QListWidget(self.gridLayoutWidget_40)
        self.model.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.model.setObjectName("model")
        self.gridLayout_12.addWidget(self.model, 1, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(340, 20, 221, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 149, 769))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayoutWidget_41 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.gridLayoutWidget_41.setGeometry(QtCore.QRect(0, 0, 141, 909))
        self.gridLayoutWidget_41.setObjectName("gridLayoutWidget_41")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_41)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.ca_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.ca_distance.setObjectName("ca_distance")
        self.gridLayout_13.addWidget(self.ca_distance, 9, 1, 1, 1)
        self.soft_sphere = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.soft_sphere.setObjectName("soft_sphere")
        self.gridLayout_13.addWidget(self.soft_sphere, 5, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_40.setObjectName("label_40")
        self.gridLayout_13.addWidget(self.label_40, 31, 0, 1, 1)
        self.nmr_distance2 = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.nmr_distance2.setObjectName("nmr_distance2")
        self.gridLayout_13.addWidget(self.nmr_distance2, 29, 1, 1, 1)
        self.nmr_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.nmr_distance.setObjectName("nmr_distance")
        self.gridLayout_13.addWidget(self.nmr_distance, 28, 1, 1, 1)
        self.min_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.min_distance.setObjectName("min_distance")
        self.gridLayout_13.addWidget(self.min_distance, 30, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_39.setObjectName("label_39")
        self.gridLayout_13.addWidget(self.label_39, 30, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_38.setObjectName("label_38")
        self.gridLayout_13.addWidget(self.label_38, 29, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 12, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_10.setObjectName("label_10")
        self.gridLayout_13.addWidget(self.label_10, 5, 0, 1, 1)
        self.lennard_jones = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.lennard_jones.setObjectName("lennard_jones")
        self.gridLayout_13.addWidget(self.lennard_jones, 6, 1, 1, 1)
        self.chi2_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.chi2_dihedral.setObjectName("chi2_dihedral")
        self.gridLayout_13.addWidget(self.chi2_dihedral, 15, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 13, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 14, 0, 1, 1)
        self.chi5_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.chi5_dihedral.setObjectName("chi5_dihedral")
        self.gridLayout_13.addWidget(self.chi5_dihedral, 18, 1, 1, 1)
        self.chi3_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.chi3_dihedral.setObjectName("chi3_dihedral")
        self.gridLayout_13.addWidget(self.chi3_dihedral, 16, 1, 1, 1)
        self.sd_sd_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.sd_sd_distance.setObjectName("sd_sd_distance")
        self.gridLayout_13.addWidget(self.sd_sd_distance, 26, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_33.setObjectName("label_33")
        self.gridLayout_13.addWidget(self.label_33, 24, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_32.setObjectName("label_32")
        self.gridLayout_13.addWidget(self.label_32, 23, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_31.setObjectName("label_31")
        self.gridLayout_13.addWidget(self.label_31, 22, 0, 1, 1)
        self.upper_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.upper_distance.setObjectName("upper_distance")
        self.gridLayout_13.addWidget(self.upper_distance, 23, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_30.setObjectName("label_30")
        self.gridLayout_13.addWidget(self.label_30, 21, 0, 1, 1)
        self.disulfide_angle = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.disulfide_angle.setObjectName("disulfide_angle")
        self.gridLayout_13.addWidget(self.disulfide_angle, 20, 1, 1, 1)
        self.disulfide_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.disulfide_dihedral.setObjectName("disulfide_dihedral")
        self.gridLayout_13.addWidget(self.disulfide_dihedral, 21, 1, 1, 1)
        self.lower_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.lower_distance.setObjectName("lower_distance")
        self.gridLayout_13.addWidget(self.lower_distance, 22, 1, 1, 1)
        self.disulfide_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.disulfide_distance.setObjectName("disulfide_distance")
        self.gridLayout_13.addWidget(self.disulfide_distance, 19, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_29.setObjectName("label_29")
        self.gridLayout_13.addWidget(self.label_29, 20, 0, 1, 1)
        self.sd_mn_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.sd_mn_distance.setObjectName("sd_mn_distance")
        self.gridLayout_13.addWidget(self.sd_mn_distance, 24, 1, 1, 1)
        self.psi_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.psi_dihedral.setObjectName("psi_dihedral")
        self.gridLayout_13.addWidget(self.psi_dihedral, 12, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 4, 0, 1, 1)
        self.h_bond = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.h_bond.setObjectName("h_bond")
        self.gridLayout_13.addWidget(self.h_bond, 8, 1, 1, 1)
        self.improper = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.improper.setObjectName("improper")
        self.gridLayout_13.addWidget(self.improper, 4, 1, 1, 1)
        self.dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.dihedral.setObjectName("dihedral")
        self.gridLayout_13.addWidget(self.dihedral, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_28.setObjectName("label_28")
        self.gridLayout_13.addWidget(self.label_28, 19, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 8, 0, 1, 1)
        self.coulomb = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.coulomb.setObjectName("coulomb")
        self.gridLayout_13.addWidget(self.coulomb, 7, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_20.setObjectName("label_20")
        self.gridLayout_13.addWidget(self.label_20, 11, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_34.setObjectName("label_34")
        self.gridLayout_13.addWidget(self.label_34, 25, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_37.setObjectName("label_37")
        self.gridLayout_13.addWidget(self.label_37, 28, 0, 1, 1)
        self.xy_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.xy_distance.setObjectName("xy_distance")
        self.gridLayout_13.addWidget(self.xy_distance, 27, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_36.setObjectName("label_36")
        self.gridLayout_13.addWidget(self.label_36, 27, 0, 1, 1)
        self.phi_psi_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.phi_psi_dihedral.setObjectName("phi_psi_dihedral")
        self.gridLayout_13.addWidget(self.phi_psi_dihedral, 25, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 7, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_35.setObjectName("label_35")
        self.gridLayout_13.addWidget(self.label_35, 26, 0, 1, 1)
        self.bond = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.bond.setObjectName("bond")
        self.gridLayout_13.addWidget(self.bond, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_6.setObjectName("label_6")
        self.gridLayout_13.addWidget(self.label_6, 1, 0, 1, 1)
        self.default_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.default_2.setObjectName("default_2")
        self.gridLayout_13.addWidget(self.default_2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_7.setObjectName("label_7")
        self.gridLayout_13.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_19.setObjectName("label_19")
        self.gridLayout_13.addWidget(self.label_19, 10, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_8.setObjectName("label_8")
        self.gridLayout_13.addWidget(self.label_8, 3, 0, 1, 1)
        self.angle = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.angle.setObjectName("angle")
        self.gridLayout_13.addWidget(self.angle, 2, 1, 1, 1)
        self.chi4_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.chi4_dihedral.setObjectName("chi4_dihedral")
        self.gridLayout_13.addWidget(self.chi4_dihedral, 17, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 15, 0, 1, 1)
        self.omega_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.omega_dihedral.setObjectName("omega_dihedral")
        self.gridLayout_13.addWidget(self.omega_dihedral, 13, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 18, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_26.setObjectName("label_26")
        self.gridLayout_13.addWidget(self.label_26, 17, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 9, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 16, 0, 1, 1)
        self.n_o_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.n_o_distance.setObjectName("n_o_distance")
        self.gridLayout_13.addWidget(self.n_o_distance, 10, 1, 1, 1)
        self.phi_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.phi_dihedral.setObjectName("phi_dihedral")
        self.gridLayout_13.addWidget(self.phi_dihedral, 11, 1, 1, 1)
        self.chi1_dihedral = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.chi1_dihedral.setObjectName("chi1_dihedral")
        self.gridLayout_13.addWidget(self.chi1_dihedral, 14, 1, 1, 1)
        self.nonbond_spline = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.nonbond_spline.setObjectName("nonbond_spline")
        self.gridLayout_13.addWidget(self.nonbond_spline, 31, 1, 1, 1)
        self.absposition = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.absposition.setObjectName("absposition")
        self.gridLayout_13.addWidget(self.absposition, 34, 1, 1, 1)
        self.SAXS = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.SAXS.setObjectName("SAXS")
        self.gridLayout_13.addWidget(self.SAXS, 36, 1, 1, 1)
        self.dihedral_diff = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.dihedral_diff.setObjectName("dihedral_diff")
        self.gridLayout_13.addWidget(self.dihedral_diff, 35, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_43.setObjectName("label_43")
        self.gridLayout_13.addWidget(self.label_43, 34, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_41.setObjectName("label_41")
        self.gridLayout_13.addWidget(self.label_41, 32, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_44.setObjectName("label_44")
        self.gridLayout_13.addWidget(self.label_44, 35, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_42.setObjectName("label_42")
        self.gridLayout_13.addWidget(self.label_42, 33, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_45.setObjectName("label_45")
        self.gridLayout_13.addWidget(self.label_45, 36, 0, 1, 1)
        self.density = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.density.setObjectName("density")
        self.gridLayout_13.addWidget(self.density, 33, 1, 1, 1)
        self.accessibility = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.accessibility.setObjectName("accessibility")
        self.gridLayout_13.addWidget(self.accessibility, 32, 1, 1, 1)
        self.symmetry = QtWidgets.QLineEdit(self.gridLayoutWidget_41)
        self.symmetry.setObjectName("symmetry")
        self.gridLayout_13.addWidget(self.symmetry, 37, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_41)
        self.label_46.setObjectName("label_46")
        self.gridLayout_13.addWidget(self.label_46, 37, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(580, 20, 160, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.maxAtomShiftLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.maxAtomShiftLabel.setObjectName("maxAtomShiftLabel")
        self.gridLayout_3.addWidget(self.maxAtomShiftLabel, 2, 0, 1, 1)
        self.mdTimeStep = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.mdTimeStep.setObjectName("mdTimeStep")
        self.gridLayout_3.addWidget(self.mdTimeStep, 4, 1, 1, 1)
        self.minAtomShift = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.minAtomShift.setObjectName("minAtomShift")
        self.gridLayout_3.addWidget(self.minAtomShift, 1, 1, 1, 1)
        self.maxAtomShift = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.maxAtomShift.setObjectName("maxAtomShift")
        self.gridLayout_3.addWidget(self.maxAtomShift, 2, 1, 1, 1)
        self.capAtomShiftLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.capAtomShiftLabel.setObjectName("capAtomShiftLabel")
        self.gridLayout_3.addWidget(self.capAtomShiftLabel, 3, 0, 1, 1)
        self.capAtomShift = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.capAtomShift.setObjectName("capAtomShift")
        self.gridLayout_3.addWidget(self.capAtomShift, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.restraint = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.restraint.setObjectName("restraint")
        self.gridLayout_3.addWidget(self.restraint, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.mdTimeStepLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.mdTimeStepLabel.setObjectName("mdTimeStepLabel")
        self.gridLayout_3.addWidget(self.mdTimeStepLabel, 4, 0, 1, 1)
        self.temperatureLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.gridLayout_3.addWidget(self.temperatureLabel, 5, 0, 1, 1)
        self.temperature = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.temperature.setObjectName("temperature")
        self.gridLayout_3.addWidget(self.temperature, 5, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(760, 20, 194, 47))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.maxIter = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.maxIter.setObjectName("maxIter")
        self.gridLayout_4.addWidget(self.maxIter, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 0, 1, 1, 1)
        self.From = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.From.setObjectName("From")
        self.gridLayout_8.addWidget(self.From, 0, 0, 1, 1)
        self.To = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.To.setObjectName("To")
        self.gridLayout_8.addWidget(self.To, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_8, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Optimize Back Bone"))
        self.optBackBoneBut.setText(_translate("Form", "Optimize back bone"))
        self.backBone_remove.setText(_translate("Form", "Remove"))
        self.label.setText(_translate("Form", "Optimization method:"))
        self.label_2.setText(_translate("Form", "Model:"))
        self.label_3.setToolTip(_translate("Form", "<html><head/><body><p>Specifies scaling factors for the physical restraint types, if you do not want to use the defaults.</p></body></html>"))
        self.label_3.setText(_translate("Form", "Scadule scale:"))
        self.label_40.setText(_translate("Form", "Nonbond_Spline:"))
        self.label_39.setText(_translate("Form", "Min_Distance:"))
        self.label_38.setText(_translate("Form", "NMR_Distance2:"))
        self.label_12.setText(_translate("Form", "Lennard_Jones:"))
        self.label_21.setText(_translate("Form", "Psi_Dihedral:"))
        self.label_10.setText(_translate("Form", "Soft_Sphere:"))
        self.label_22.setText(_translate("Form", "Omega_Dihedral:"))
        self.label_4.setText(_translate("Form", "Default:"))
        self.label_23.setText(_translate("Form", "Chi1_Dihedral:"))
        self.label_33.setText(_translate("Form", "SD_MN_Distance:"))
        self.label_32.setText(_translate("Form", "Upper_Distance:"))
        self.label_31.setText(_translate("Form", "Lower_Distance:"))
        self.label_30.setText(_translate("Form", "Disulfide_Dihedral:"))
        self.label_29.setText(_translate("Form", "Disulfide_Angle:"))
        self.label_9.setText(_translate("Form", "Improper:"))
        self.label_28.setText(_translate("Form", "Disulfide_Distance:"))
        self.label_14.setText(_translate("Form", "H_Bond:"))
        self.label_20.setText(_translate("Form", "Phi_Dihedral:"))
        self.label_34.setText(_translate("Form", "Phi_Psi_Dihedral:"))
        self.label_37.setText(_translate("Form", "NMR_Distance:"))
        self.label_36.setText(_translate("Form", "XY_Distance:"))
        self.label_13.setText(_translate("Form", "Coulomb:"))
        self.label_35.setText(_translate("Form", "SD_SD_Distance:"))
        self.label_6.setText(_translate("Form", "Bond:"))
        self.label_7.setText(_translate("Form", "Angle:"))
        self.label_19.setText(_translate("Form", "N_O_Distance:"))
        self.label_8.setText(_translate("Form", "Dihedral:"))
        self.label_24.setText(_translate("Form", "Chi2_Dihedral:"))
        self.label_27.setText(_translate("Form", "Chi5_Dihedral:"))
        self.label_26.setText(_translate("Form", "Chi4_Dihedral:"))
        self.label_15.setText(_translate("Form", "CA_Distance:"))
        self.label_25.setText(_translate("Form", "Chi3_Dihedral:"))
        self.label_43.setText(_translate("Form", "Absposition:"))
        self.label_41.setText(_translate("Form", "Accessibility:"))
        self.label_44.setText(_translate("Form", "Dihedral_Diff:"))
        self.label_42.setText(_translate("Form", "Density:"))
        self.label_45.setText(_translate("Form", "SAXS:"))
        self.label_46.setText(_translate("Form", "Symmetry:"))
        self.maxAtomShiftLabel.setText(_translate("Form", "Max atom shift:"))
        self.capAtomShiftLabel.setToolTip(_translate("Form", "<html><head/><body><p>Atomic shifts along one axis are limited by this parameter (in angstroms).</p></body></html>"))
        self.capAtomShiftLabel.setText(_translate("Form", "Cap atom shift:"))
        self.label_11.setToolTip(_translate("Form", "<html><head/><body><p>It is a convergence criterion for the optimization. When the maximal atomic shift is less than the specified value, the optimization is finished regardless of the number of optimization cycles or function value and its change.</p></body></html>"))
        self.label_11.setText(_translate("Form", "Min atom shift:"))
        self.label_5.setText(_translate("Form", "Restraint file:"))
        self.mdTimeStepLabel.setToolTip(_translate("Form", "<html><head/><body><p>Time step in femtoseconds.</p></body></html>"))
        self.mdTimeStepLabel.setText(_translate("Form", "MD time step:"))
        self.temperatureLabel.setToolTip(_translate("Form", "<html><head/><body><p>Temperature of the system in Kelvin.</p></body></html>"))
        self.temperatureLabel.setText(_translate("Form", "Temprature:"))
        self.label_16.setToolTip(_translate("Form", "<html><head/><body><p>It is used to prevent a waste of CPU time in the optimization.</p></body></html>"))
        self.label_16.setText(_translate("Form", "Max iteration:"))
        self.label_17.setToolTip(_translate("Form", "<html><head/><body><p>Determines what atom pairs can possibly occur in the non-bonded atom pairs list used for dynamic restraints.</p></body></html>"))
        self.label_17.setText(_translate("Form", "Residue span range:"))
        self.label_18.setText(_translate("Form", "To"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

