# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpl_prepare_temp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(978, 432)
        Form.setMouseTracking(True)
        self.prepare_toolBox = QtWidgets.QToolBox(Form)
        self.prepare_toolBox.setGeometry(QtCore.QRect(0, 0, 1001, 421))
        self.prepare_toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.prepare_toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.prepare_toolBox.setObjectName("prepare_toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 1001, 373))
        self.page.setMouseTracking(True)
        self.page.setObjectName("page")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(300, 80, 151, 21))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.removeHETATM = QtWidgets.QComboBox(self.horizontalLayoutWidget_9)
        self.removeHETATM.setObjectName("removeHETATM")
        self.horizontalLayout_9.addWidget(self.removeHETATM)
        self.gridLayoutWidget = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(300, 50, 151, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.layout_fromTo = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.layout_fromTo.setContentsMargins(0, 0, 0, 0)
        self.layout_fromTo.setObjectName("layout_fromTo")
        self.segFrom = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.segFrom.setEnabled(False)
        self.segFrom.setObjectName("segFrom")
        self.layout_fromTo.addWidget(self.segFrom, 0, 0, 1, 1)
        self.segToLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.segToLabel.setEnabled(False)
        self.segToLabel.setObjectName("segToLabel")
        self.layout_fromTo.addWidget(self.segToLabel, 0, 2, 1, 1)
        self.chainFrom = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.chainFrom.setEnabled(False)
        self.chainFrom.setObjectName("chainFrom")
        self.layout_fromTo.addWidget(self.chainFrom, 0, 1, 1, 1)
        self.segTo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.segTo.setEnabled(False)
        self.segTo.setObjectName("segTo")
        self.layout_fromTo.addWidget(self.segTo, 0, 3, 1, 1)
        self.chainTo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.chainTo.setEnabled(False)
        self.chainTo.setObjectName("chainTo")
        self.layout_fromTo.addWidget(self.chainTo, 0, 4, 1, 1)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(300, 130, 151, 21))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.patchTerminal = QtWidgets.QComboBox(self.horizontalLayoutWidget_11)
        self.patchTerminal.setObjectName("patchTerminal")
        self.horizontalLayout_11.addWidget(self.patchTerminal)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(200, 130, 94, 21))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(300, 0, 151, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reNumberRes = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.reNumberRes.setObjectName("reNumberRes")
        self.horizontalLayout_3.addWidget(self.reNumberRes)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(200, 50, 82, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.segFromLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.segFromLabel.setEnabled(False)
        self.segFromLabel.setObjectName("segFromLabel")
        self.horizontalLayout_10.addWidget(self.segFromLabel)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(200, 30, 87, 21))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 181, 161))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PDB = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.PDB.setObjectName("PDB")
        self.horizontalLayout.addWidget(self.PDB)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(300, 30, 151, 21))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.segmentRes = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.segmentRes.setObjectName("segmentRes")
        self.horizontalLayout_5.addWidget(self.segmentRes)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(200, 80, 82, 21))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(0, 200, 991, 31))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.repairBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_20)
        self.repairBut.setObjectName("repairBut")
        self.horizontalLayout_20.addWidget(self.repairBut)
        self.rep_remove_file = QtWidgets.QPushButton(self.horizontalLayoutWidget_20)
        self.rep_remove_file.setObjectName("rep_remove_file")
        self.horizontalLayout_20.addWidget(self.rep_remove_file)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(200, 0, 82, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(300, 100, 151, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.addPatch = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        self.addPatch.setObjectName("addPatch")
        self.horizontalLayout_7.addWidget(self.addPatch)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(200, 100, 82, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.horizontalLayoutWidget_21 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_21.setGeometry(QtCore.QRect(470, 0, 521, 171))
        self.horizontalLayoutWidget_21.setObjectName("horizontalLayoutWidget_21")
        self.layout_addPatch = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_21)
        self.layout_addPatch.setContentsMargins(0, 0, 0, 0)
        self.layout_addPatch.setObjectName("layout_addPatch")
        self.frame_addPatch = QtWidgets.QFrame(self.horizontalLayoutWidget_21)
        self.frame_addPatch.setEnabled(False)
        self.frame_addPatch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_addPatch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_addPatch.setObjectName("frame_addPatch")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.frame_addPatch)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(30, 0, 41, 161))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.chainPDB = QtWidgets.QListWidget(self.horizontalLayoutWidget_13)
        self.chainPDB.setObjectName("chainPDB")
        self.horizontalLayout_22.addWidget(self.chainPDB)
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.frame_addPatch)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(220, 0, 63, 161))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.patchType = QtWidgets.QListWidget(self.horizontalLayoutWidget_18)
        self.patchType.setObjectName("patchType")
        self.horizontalLayout_23.addWidget(self.patchType)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.frame_addPatch)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(170, 0, 51, 31))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_24.addWidget(self.label_10)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.frame_addPatch)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(80, 20, 81, 141))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.resNumber = QtWidgets.QListWidget(self.horizontalLayoutWidget_16)
        self.resNumber.setObjectName("resNumber")
        self.horizontalLayout_25.addWidget(self.resNumber)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_addPatch)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 0, 41, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.addBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addBut.setObjectName("addBut")
        self.verticalLayout_2.addWidget(self.addBut)
        self.minBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.minBut.setObjectName("minBut")
        self.verticalLayout_2.addWidget(self.minBut)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.frame_addPatch)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(80, 0, 81, 21))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.searchRes = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.searchRes.setObjectName("searchRes")
        self.horizontalLayout_26.addWidget(self.searchRes)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.frame_addPatch)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(0, 0, 32, 31))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_27.addWidget(self.label_11)
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.frame_addPatch)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(340, 0, 161, 161))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pdbChainAdded = QtWidgets.QListWidget(self.horizontalLayoutWidget_19)
        self.pdbChainAdded.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.pdbChainAdded.setObjectName("pdbChainAdded")
        self.horizontalLayout_28.addWidget(self.pdbChainAdded)
        self.layout_addPatch.addWidget(self.frame_addPatch)
        self.horizontalLayoutWidget_91 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_91.setGeometry(QtCore.QRect(0, 182, 991, 22))
        self.horizontalLayoutWidget_91.setObjectName("horizontalLayoutWidget_91")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_91)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.msgLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_91)
        self.msgLabel.setText("")
        self.msgLabel.setObjectName("msgLabel")
        self.horizontalLayout_21.addWidget(self.msgLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.prepare_toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1001, 373))
        self.page_2.setObjectName("page_2")
        self.horizontalLayoutWidget_22 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(10, 0, 171, 161))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.alignPDB = QtWidgets.QListWidget(self.horizontalLayoutWidget_22)
        self.alignPDB.setObjectName("alignPDB")
        self.horizontalLayout_15.addWidget(self.alignPDB)
        self.horizontalLayoutWidget_23 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_23.setGeometry(QtCore.QRect(190, 0, 63, 161))
        self.horizontalLayoutWidget_23.setObjectName("horizontalLayoutWidget_23")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_23)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.alignChainPDB = QtWidgets.QListWidget(self.horizontalLayoutWidget_23)
        self.alignChainPDB.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.alignChainPDB.setObjectName("alignChainPDB")
        self.horizontalLayout_16.addWidget(self.alignChainPDB)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(260, 0, 41, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.alignAddBut = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.alignAddBut.setObjectName("alignAddBut")
        self.verticalLayout_5.addWidget(self.alignAddBut)
        self.alignMinBut = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.alignMinBut.setObjectName("alignMinBut")
        self.verticalLayout_5.addWidget(self.alignMinBut)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayoutWidget_24 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_24.setGeometry(QtCore.QRect(310, 0, 191, 161))
        self.horizontalLayoutWidget_24.setObjectName("horizontalLayoutWidget_24")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_24)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.alignpdbChainAdded = QtWidgets.QListWidget(self.horizontalLayoutWidget_24)
        self.alignpdbChainAdded.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.alignpdbChainAdded.setObjectName("alignpdbChainAdded")
        self.horizontalLayout_17.addWidget(self.alignpdbChainAdded)
        self.horizontalLayoutWidget_25 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_25.setGeometry(QtCore.QRect(520, 0, 71, 21))
        self.horizontalLayoutWidget_25.setObjectName("horizontalLayoutWidget_25")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_25)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_25)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_18.addWidget(self.label_5)
        self.horizontalLayoutWidget_26 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_26.setGeometry(QtCore.QRect(600, 0, 91, 21))
        self.horizontalLayoutWidget_26.setObjectName("horizontalLayoutWidget_26")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_26)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.alignType = QtWidgets.QComboBox(self.horizontalLayoutWidget_26)
        self.alignType.setObjectName("alignType")
        self.horizontalLayout_19.addWidget(self.alignType)
        self.horizontalLayoutWidget_28 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_28.setGeometry(QtCore.QRect(520, 20, 71, 31))
        self.horizontalLayoutWidget_28.setObjectName("horizontalLayoutWidget_28")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_28)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_28)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_35.addWidget(self.label_8)
        self.horizontalLayoutWidget_27 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_27.setGeometry(QtCore.QRect(600, 20, 91, 31))
        self.horizontalLayoutWidget_27.setObjectName("horizontalLayoutWidget_27")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_27)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.localGlobal = QtWidgets.QComboBox(self.horizontalLayoutWidget_27)
        self.localGlobal.setObjectName("localGlobal")
        self.horizontalLayout_34.addWidget(self.localGlobal)
        self.horizontalLayoutWidget_30 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_30.setGeometry(QtCore.QRect(520, 50, 71, 21))
        self.horizontalLayoutWidget_30.setObjectName("horizontalLayoutWidget_30")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_30)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_30)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_41.addWidget(self.label_15)
        self.horizontalLayoutWidget_29 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_29.setGeometry(QtCore.QRect(600, 50, 91, 21))
        self.horizontalLayoutWidget_29.setObjectName("horizontalLayoutWidget_29")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_29)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.matrix = QtWidgets.QComboBox(self.horizontalLayoutWidget_29)
        self.matrix.setObjectName("matrix")
        self.horizontalLayout_40.addWidget(self.matrix)
        self.horizontalLayoutWidget_32 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_32.setGeometry(QtCore.QRect(520, 70, 71, 31))
        self.horizontalLayoutWidget_32.setObjectName("horizontalLayoutWidget_32")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_32)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_32)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_43.addWidget(self.label_16)
        self.horizontalLayoutWidget_31 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_31.setGeometry(QtCore.QRect(600, 70, 91, 31))
        self.horizontalLayoutWidget_31.setObjectName("horizontalLayoutWidget_31")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_31)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.gapFunction = QtWidgets.QComboBox(self.horizontalLayoutWidget_31)
        self.gapFunction.setObjectName("gapFunction")
        self.horizontalLayout_42.addWidget(self.gapFunction)
        self.horizontalLayoutWidget_33 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_33.setGeometry(QtCore.QRect(600, 100, 91, 21))
        self.horizontalLayoutWidget_33.setObjectName("horizontalLayoutWidget_33")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_33)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.gapOpen1d = QtWidgets.QLineEdit(self.horizontalLayoutWidget_33)
        self.gapOpen1d.setObjectName("gapOpen1d")
        self.horizontalLayout_44.addWidget(self.gapOpen1d)
        self.horizontalLayoutWidget_34 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_34.setGeometry(QtCore.QRect(520, 100, 71, 21))
        self.horizontalLayoutWidget_34.setObjectName("horizontalLayoutWidget_34")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_34)
        self.horizontalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_34)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_45.addWidget(self.label_17)
        self.horizontalLayoutWidget_35 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_35.setGeometry(QtCore.QRect(600, 120, 91, 31))
        self.horizontalLayoutWidget_35.setObjectName("horizontalLayoutWidget_35")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_35)
        self.horizontalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.gapExten1d = QtWidgets.QLineEdit(self.horizontalLayoutWidget_35)
        self.gapExten1d.setObjectName("gapExten1d")
        self.horizontalLayout_46.addWidget(self.gapExten1d)
        self.horizontalLayoutWidget_36 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_36.setGeometry(QtCore.QRect(520, 120, 76, 31))
        self.horizontalLayoutWidget_36.setObjectName("horizontalLayoutWidget_36")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_36)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_36)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_47.addWidget(self.label_18)
        self.horizontalLayoutWidget_38 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_38.setGeometry(QtCore.QRect(710, 0, 87, 21))
        self.horizontalLayoutWidget_38.setObjectName("horizontalLayoutWidget_38")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_38)
        self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_38)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_51.addWidget(self.label_20)
        self.horizontalLayoutWidget_37 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_37.setGeometry(QtCore.QRect(870, 0, 91, 21))
        self.horizontalLayoutWidget_37.setObjectName("horizontalLayoutWidget_37")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_37)
        self.horizontalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.gapPenalt2dHelix = QtWidgets.QLineEdit(self.horizontalLayoutWidget_37)
        self.gapPenalt2dHelix.setObjectName("gapPenalt2dHelix")
        self.horizontalLayout_50.addWidget(self.gapPenalt2dHelix)
        self.horizontalLayoutWidget_40 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_40.setGeometry(QtCore.QRect(710, 20, 86, 31))
        self.horizontalLayoutWidget_40.setObjectName("horizontalLayoutWidget_40")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_40)
        self.horizontalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_40)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_53.addWidget(self.label_21)
        self.horizontalLayoutWidget_39 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_39.setGeometry(QtCore.QRect(870, 20, 91, 31))
        self.horizontalLayoutWidget_39.setObjectName("horizontalLayoutWidget_39")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_39)
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.gapPenalt2dBeta = QtWidgets.QLineEdit(self.horizontalLayoutWidget_39)
        self.gapPenalt2dBeta.setObjectName("gapPenalt2dBeta")
        self.horizontalLayout_52.addWidget(self.gapPenalt2dBeta)
        self.horizontalLayoutWidget_42 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_42.setGeometry(QtCore.QRect(870, 50, 91, 21))
        self.horizontalLayoutWidget_42.setObjectName("horizontalLayoutWidget_42")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_42)
        self.horizontalLayout_55.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.gapPenalt2dAccess = QtWidgets.QLineEdit(self.horizontalLayoutWidget_42)
        self.gapPenalt2dAccess.setObjectName("gapPenalt2dAccess")
        self.horizontalLayout_55.addWidget(self.gapPenalt2dAccess)
        self.horizontalLayoutWidget_41 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_41.setGeometry(QtCore.QRect(710, 50, 116, 21))
        self.horizontalLayoutWidget_41.setObjectName("horizontalLayoutWidget_41")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_41)
        self.horizontalLayout_54.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_41)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_54.addWidget(self.label_22)
        self.horizontalLayoutWidget_44 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_44.setGeometry(QtCore.QRect(870, 70, 91, 31))
        self.horizontalLayoutWidget_44.setObjectName("horizontalLayoutWidget_44")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_44)
        self.horizontalLayout_57.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.gapPenalt2dStright = QtWidgets.QLineEdit(self.horizontalLayoutWidget_44)
        self.gapPenalt2dStright.setObjectName("gapPenalt2dStright")
        self.horizontalLayout_57.addWidget(self.gapPenalt2dStright)
        self.horizontalLayoutWidget_43 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_43.setGeometry(QtCore.QRect(710, 70, 117, 31))
        self.horizontalLayoutWidget_43.setObjectName("horizontalLayoutWidget_43")
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_43)
        self.horizontalLayout_56.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_43)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_56.addWidget(self.label_23)
        self.horizontalLayoutWidget_46 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_46.setGeometry(QtCore.QRect(710, 100, 155, 21))
        self.horizontalLayoutWidget_46.setObjectName("horizontalLayoutWidget_46")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_46)
        self.horizontalLayout_61.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_46)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_61.addWidget(self.label_25)
        self.horizontalLayoutWidget_45 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_45.setGeometry(QtCore.QRect(870, 100, 91, 21))
        self.horizontalLayoutWidget_45.setObjectName("horizontalLayoutWidget_45")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_45)
        self.horizontalLayout_60.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.gapPenalt2dCACA = QtWidgets.QLineEdit(self.horizontalLayoutWidget_45)
        self.gapPenalt2dCACA.setObjectName("gapPenalt2dCACA")
        self.horizontalLayout_60.addWidget(self.gapPenalt2dCACA)
        self.horizontalLayoutWidget_48 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_48.setGeometry(QtCore.QRect(710, 120, 117, 31))
        self.horizontalLayoutWidget_48.setObjectName("horizontalLayoutWidget_48")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_48)
        self.horizontalLayout_63.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_48)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_63.addWidget(self.label_26)
        self.horizontalLayoutWidget_47 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_47.setGeometry(QtCore.QRect(870, 121, 91, 31))
        self.horizontalLayoutWidget_47.setObjectName("horizontalLayoutWidget_47")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_47)
        self.horizontalLayout_62.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.gapPenalt2dDstMin = QtWidgets.QLineEdit(self.horizontalLayoutWidget_47)
        self.gapPenalt2dDstMin.setObjectName("gapPenalt2dDstMin")
        self.horizontalLayout_62.addWidget(self.gapPenalt2dDstMin)
        self.horizontalLayoutWidget_50 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_50.setGeometry(QtCore.QRect(10, 200, 117, 21))
        self.horizontalLayoutWidget_50.setObjectName("horizontalLayoutWidget_50")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_50)
        self.horizontalLayout_67.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_50)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_67.addWidget(self.label_28)
        self.horizontalLayoutWidget_49 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_49.setGeometry(QtCore.QRect(140, 200, 91, 21))
        self.horizontalLayoutWidget_49.setObjectName("horizontalLayoutWidget_49")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_49)
        self.horizontalLayout_66.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.gapPenalt2dDstPower = QtWidgets.QLineEdit(self.horizontalLayoutWidget_49)
        self.gapPenalt2dDstPower.setObjectName("gapPenalt2dDstPower")
        self.horizontalLayout_66.addWidget(self.gapPenalt2dDstPower)
        self.horizontalLayoutWidget_52 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_52.setGeometry(QtCore.QRect(10, 220, 132, 31))
        self.horizontalLayoutWidget_52.setObjectName("horizontalLayoutWidget_52")
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_52)
        self.horizontalLayout_69.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_52)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_69.addWidget(self.label_29)
        self.horizontalLayoutWidget_51 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_51.setGeometry(QtCore.QRect(140, 220, 91, 31))
        self.horizontalLayoutWidget_51.setObjectName("horizontalLayoutWidget_51")
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_51)
        self.horizontalLayout_68.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.gapPenalt2dStrucProfile = QtWidgets.QLineEdit(self.horizontalLayoutWidget_51)
        self.gapPenalt2dStrucProfile.setObjectName("gapPenalt2dStrucProfile")
        self.horizontalLayout_68.addWidget(self.gapPenalt2dStrucProfile)
        self.horizontalLayoutWidget_56 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_56.setGeometry(QtCore.QRect(140, 270, 91, 31))
        self.horizontalLayoutWidget_56.setObjectName("horizontalLayoutWidget_56")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_56)
        self.horizontalLayout_73.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.gapExten3d = QtWidgets.QLineEdit(self.horizontalLayoutWidget_56)
        self.gapExten3d.setObjectName("gapExten3d")
        self.horizontalLayout_73.addWidget(self.gapExten3d)
        self.horizontalLayoutWidget_55 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_55.setGeometry(QtCore.QRect(10, 250, 71, 21))
        self.horizontalLayoutWidget_55.setObjectName("horizontalLayoutWidget_55")
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_55)
        self.horizontalLayout_72.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_55)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_72.addWidget(self.label_31)
        self.horizontalLayoutWidget_54 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_54.setGeometry(QtCore.QRect(140, 250, 91, 21))
        self.horizontalLayoutWidget_54.setObjectName("horizontalLayoutWidget_54")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_54)
        self.horizontalLayout_71.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.gapOpen3d = QtWidgets.QLineEdit(self.horizontalLayoutWidget_54)
        self.gapOpen3d.setObjectName("gapOpen3d")
        self.horizontalLayout_71.addWidget(self.gapOpen3d)
        self.horizontalLayoutWidget_53 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_53.setGeometry(QtCore.QRect(10, 270, 76, 31))
        self.horizontalLayoutWidget_53.setObjectName("horizontalLayoutWidget_53")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_53)
        self.horizontalLayout_70.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_53)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_70.addWidget(self.label_30)
        self.horizontalLayoutWidget_57 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_57.setGeometry(QtCore.QRect(250, 250, 71, 21))
        self.horizontalLayoutWidget_57.setObjectName("horizontalLayoutWidget_57")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_57)
        self.horizontalLayout_74.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_57)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_74.addWidget(self.label_32)
        self.horizontalLayoutWidget_58 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_58.setGeometry(QtCore.QRect(330, 270, 91, 31))
        self.horizontalLayoutWidget_58.setObjectName("horizontalLayoutWidget_58")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_58)
        self.horizontalLayout_75.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.overhang = QtWidgets.QLineEdit(self.horizontalLayoutWidget_58)
        self.overhang.setObjectName("overhang")
        self.horizontalLayout_75.addWidget(self.overhang)
        self.horizontalLayoutWidget_59 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_59.setGeometry(QtCore.QRect(330, 200, 91, 21))
        self.horizontalLayoutWidget_59.setObjectName("horizontalLayoutWidget_59")
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_59)
        self.horizontalLayout_76.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.maxgapLen = QtWidgets.QLineEdit(self.horizontalLayoutWidget_59)
        self.maxgapLen.setObjectName("maxgapLen")
        self.horizontalLayout_76.addWidget(self.maxgapLen)
        self.horizontalLayoutWidget_60 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_60.setGeometry(QtCore.QRect(330, 250, 91, 21))
        self.horizontalLayoutWidget_60.setObjectName("horizontalLayoutWidget_60")
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_60)
        self.horizontalLayout_77.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.gapGapScore = QtWidgets.QLineEdit(self.horizontalLayoutWidget_60)
        self.gapGapScore.setObjectName("gapGapScore")
        self.horizontalLayout_77.addWidget(self.gapGapScore)
        self.horizontalLayoutWidget_61 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_61.setGeometry(QtCore.QRect(330, 220, 91, 31))
        self.horizontalLayoutWidget_61.setObjectName("horizontalLayoutWidget_61")
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_61)
        self.horizontalLayout_78.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.gapResScore = QtWidgets.QLineEdit(self.horizontalLayoutWidget_61)
        self.gapResScore.setObjectName("gapResScore")
        self.horizontalLayout_78.addWidget(self.gapResScore)
        self.horizontalLayoutWidget_62 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_62.setGeometry(QtCore.QRect(250, 270, 76, 31))
        self.horizontalLayoutWidget_62.setObjectName("horizontalLayoutWidget_62")
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_62)
        self.horizontalLayout_79.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_62)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_79.addWidget(self.label_33)
        self.horizontalLayoutWidget_63 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_63.setGeometry(QtCore.QRect(250, 200, 71, 21))
        self.horizontalLayoutWidget_63.setObjectName("horizontalLayoutWidget_63")
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_63)
        self.horizontalLayout_80.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_63)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_80.addWidget(self.label_34)
        self.horizontalLayoutWidget_64 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_64.setGeometry(QtCore.QRect(250, 220, 81, 31))
        self.horizontalLayoutWidget_64.setObjectName("horizontalLayoutWidget_64")
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_64)
        self.horizontalLayout_81.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_64)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_81.addWidget(self.label_35)
        self.horizontalLayoutWidget_72 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_72.setGeometry(QtCore.QRect(530, 200, 91, 21))
        self.horizontalLayoutWidget_72.setObjectName("horizontalLayoutWidget_72")
        self.horizontalLayout_89 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_72)
        self.horizontalLayout_89.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_89.setObjectName("horizontalLayout_89")
        self.autoOverhang = QtWidgets.QComboBox(self.horizontalLayoutWidget_72)
        self.autoOverhang.setObjectName("autoOverhang")
        self.horizontalLayout_89.addWidget(self.autoOverhang)
        self.horizontalLayoutWidget_65 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_65.setGeometry(QtCore.QRect(440, 220, 83, 31))
        self.horizontalLayoutWidget_65.setObjectName("horizontalLayoutWidget_65")
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_65)
        self.horizontalLayout_82.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.autoOverHangLimlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_65)
        self.autoOverHangLimlabel.setEnabled(False)
        self.autoOverHangLimlabel.setObjectName("autoOverHangLimlabel")
        self.horizontalLayout_82.addWidget(self.autoOverHangLimlabel)
        self.horizontalLayoutWidget_71 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_71.setGeometry(QtCore.QRect(440, 200, 71, 21))
        self.horizontalLayoutWidget_71.setObjectName("horizontalLayoutWidget_71")
        self.horizontalLayout_88 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_71)
        self.horizontalLayout_88.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_88.setObjectName("horizontalLayout_88")
        self.label_39 = QtWidgets.QLabel(self.horizontalLayoutWidget_71)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_88.addWidget(self.label_39)
        self.horizontalLayoutWidget_67 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_67.setGeometry(QtCore.QRect(530, 270, 91, 31))
        self.horizontalLayoutWidget_67.setObjectName("horizontalLayoutWidget_67")
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_67)
        self.horizontalLayout_84.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.similarityFlag = QtWidgets.QComboBox(self.horizontalLayoutWidget_67)
        self.similarityFlag.setObjectName("similarityFlag")
        self.horizontalLayout_84.addWidget(self.similarityFlag)
        self.horizontalLayoutWidget_68 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_68.setGeometry(QtCore.QRect(530, 250, 91, 21))
        self.horizontalLayoutWidget_68.setObjectName("horizontalLayoutWidget_68")
        self.horizontalLayout_85 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_68)
        self.horizontalLayout_85.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_85.setObjectName("horizontalLayout_85")
        self.overhangFactor = QtWidgets.QLineEdit(self.horizontalLayoutWidget_68)
        self.overhangFactor.setEnabled(False)
        self.overhangFactor.setObjectName("overhangFactor")
        self.horizontalLayout_85.addWidget(self.overhangFactor)
        self.horizontalLayoutWidget_70 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_70.setGeometry(QtCore.QRect(440, 250, 71, 21))
        self.horizontalLayoutWidget_70.setObjectName("horizontalLayoutWidget_70")
        self.horizontalLayout_87 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_70)
        self.horizontalLayout_87.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_87.setObjectName("horizontalLayout_87")
        self.overHangFaclabel = QtWidgets.QLabel(self.horizontalLayoutWidget_70)
        self.overHangFaclabel.setEnabled(False)
        self.overHangFaclabel.setObjectName("overHangFaclabel")
        self.horizontalLayout_87.addWidget(self.overHangFaclabel)
        self.horizontalLayoutWidget_66 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_66.setGeometry(QtCore.QRect(440, 270, 76, 31))
        self.horizontalLayoutWidget_66.setObjectName("horizontalLayoutWidget_66")
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_66)
        self.horizontalLayout_83.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.label_37 = QtWidgets.QLabel(self.horizontalLayoutWidget_66)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_83.addWidget(self.label_37)
        self.horizontalLayoutWidget_69 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_69.setGeometry(QtCore.QRect(530, 220, 91, 31))
        self.horizontalLayoutWidget_69.setObjectName("horizontalLayoutWidget_69")
        self.horizontalLayout_86 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_69)
        self.horizontalLayout_86.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_86.setObjectName("horizontalLayout_86")
        self.autoOverhangLim = QtWidgets.QLineEdit(self.horizontalLayoutWidget_69)
        self.autoOverhangLim.setEnabled(False)
        self.autoOverhangLim.setObjectName("autoOverhangLim")
        self.horizontalLayout_86.addWidget(self.autoOverhangLim)
        self.horizontalLayoutWidget_80 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_80.setGeometry(QtCore.QRect(700, 220, 91, 31))
        self.horizontalLayoutWidget_80.setObjectName("horizontalLayoutWidget_80")
        self.horizontalLayout_105 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_80)
        self.horizontalLayout_105.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_105.setObjectName("horizontalLayout_105")
        self.matrixOffset = QtWidgets.QLineEdit(self.horizontalLayoutWidget_80)
        self.matrixOffset.setEnabled(False)
        self.matrixOffset.setObjectName("matrixOffset")
        self.horizontalLayout_105.addWidget(self.matrixOffset)
        self.horizontalLayoutWidget_77 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_77.setGeometry(QtCore.QRect(700, 250, 91, 21))
        self.horizontalLayoutWidget_77.setObjectName("horizontalLayoutWidget_77")
        self.horizontalLayout_102 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_77)
        self.horizontalLayout_102.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_102.setObjectName("horizontalLayout_102")
        self.userMatrix = QtWidgets.QPushButton(self.horizontalLayoutWidget_77)
        self.userMatrix.setObjectName("userMatrix")
        self.horizontalLayout_102.addWidget(self.userMatrix)
        self.horizontalLayoutWidget_78 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_78.setGeometry(QtCore.QRect(640, 250, 51, 21))
        self.horizontalLayoutWidget_78.setObjectName("horizontalLayoutWidget_78")
        self.horizontalLayout_103 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_78)
        self.horizontalLayout_103.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_103.setObjectName("horizontalLayout_103")
        self.label_46 = QtWidgets.QLabel(self.horizontalLayoutWidget_78)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_103.addWidget(self.label_46)
        self.horizontalLayoutWidget_73 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_73.setGeometry(QtCore.QRect(700, 200, 91, 21))
        self.horizontalLayoutWidget_73.setObjectName("horizontalLayoutWidget_73")
        self.horizontalLayout_98 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_73)
        self.horizontalLayout_98.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_98.setObjectName("horizontalLayout_98")
        self.rmsCutOff = QtWidgets.QLineEdit(self.horizontalLayoutWidget_73)
        self.rmsCutOff.setObjectName("rmsCutOff")
        self.horizontalLayout_98.addWidget(self.rmsCutOff)
        self.horizontalLayoutWidget_79 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_79.setGeometry(QtCore.QRect(640, 270, 51, 31))
        self.horizontalLayoutWidget_79.setObjectName("horizontalLayoutWidget_79")
        self.horizontalLayout_104 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_79)
        self.horizontalLayout_104.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_104.setObjectName("horizontalLayout_104")
        self.userMatrixTypelabel = QtWidgets.QLabel(self.horizontalLayoutWidget_79)
        self.userMatrixTypelabel.setEnabled(False)
        self.userMatrixTypelabel.setObjectName("userMatrixTypelabel")
        self.horizontalLayout_104.addWidget(self.userMatrixTypelabel)
        self.horizontalLayoutWidget_74 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_74.setGeometry(QtCore.QRect(640, 220, 61, 31))
        self.horizontalLayoutWidget_74.setObjectName("horizontalLayoutWidget_74")
        self.horizontalLayout_99 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_74)
        self.horizontalLayout_99.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_99.setObjectName("horizontalLayout_99")
        self.matrixOffsetlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_74)
        self.matrixOffsetlabel.setEnabled(False)
        self.matrixOffsetlabel.setObjectName("matrixOffsetlabel")
        self.horizontalLayout_99.addWidget(self.matrixOffsetlabel)
        self.horizontalLayoutWidget_75 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_75.setGeometry(QtCore.QRect(640, 200, 61, 21))
        self.horizontalLayoutWidget_75.setObjectName("horizontalLayoutWidget_75")
        self.horizontalLayout_100 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_75)
        self.horizontalLayout_100.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_100.setObjectName("horizontalLayout_100")
        self.label_45 = QtWidgets.QLabel(self.horizontalLayoutWidget_75)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_100.addWidget(self.label_45)
        self.horizontalLayoutWidget_76 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_76.setGeometry(QtCore.QRect(700, 270, 91, 31))
        self.horizontalLayoutWidget_76.setObjectName("horizontalLayoutWidget_76")
        self.horizontalLayout_101 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_76)
        self.horizontalLayout_101.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_101.setObjectName("horizontalLayout_101")
        self.userMatrixType = QtWidgets.QComboBox(self.horizontalLayoutWidget_76)
        self.userMatrixType.setEnabled(False)
        self.userMatrixType.setObjectName("userMatrixType")
        self.horizontalLayout_101.addWidget(self.userMatrixType)
        self.horizontalLayoutWidget_88 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_88.setGeometry(QtCore.QRect(870, 270, 91, 31))
        self.horizontalLayoutWidget_88.setObjectName("horizontalLayoutWidget_88")
        self.horizontalLayout_113 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_88)
        self.horizontalLayout_113.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_113.setObjectName("horizontalLayout_113")
        self.seq = QtWidgets.QComboBox(self.horizontalLayoutWidget_88)
        self.seq.setObjectName("seq")
        self.horizontalLayout_113.addWidget(self.seq)
        self.horizontalLayoutWidget_82 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_82.setGeometry(QtCore.QRect(810, 250, 55, 21))
        self.horizontalLayoutWidget_82.setObjectName("horizontalLayoutWidget_82")
        self.horizontalLayout_107 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_82)
        self.horizontalLayout_107.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_107.setObjectName("horizontalLayout_107")
        self.label_48 = QtWidgets.QLabel(self.horizontalLayoutWidget_82)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_107.addWidget(self.label_48)
        self.horizontalLayoutWidget_85 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_85.setGeometry(QtCore.QRect(810, 220, 52, 31))
        self.horizontalLayoutWidget_85.setObjectName("horizontalLayoutWidget_85")
        self.horizontalLayout_110 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_85)
        self.horizontalLayout_110.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_110.setObjectName("horizontalLayout_110")
        self.label_50 = QtWidgets.QLabel(self.horizontalLayoutWidget_85)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_110.addWidget(self.label_50)
        self.horizontalLayoutWidget_83 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_83.setGeometry(QtCore.QRect(870, 200, 91, 21))
        self.horizontalLayoutWidget_83.setObjectName("horizontalLayoutWidget_83")
        self.horizontalLayout_108 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_83)
        self.horizontalLayout_108.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_108.setObjectName("horizontalLayout_108")
        self.useFit = QtWidgets.QComboBox(self.horizontalLayoutWidget_83)
        self.useFit.setObjectName("useFit")
        self.horizontalLayout_108.addWidget(self.useFit)
        self.horizontalLayoutWidget_81 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_81.setGeometry(QtCore.QRect(870, 250, 91, 21))
        self.horizontalLayoutWidget_81.setObjectName("horizontalLayoutWidget_81")
        self.horizontalLayout_106 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_81)
        self.horizontalLayout_106.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_106.setObjectName("horizontalLayout_106")
        self.dendrogram = QtWidgets.QComboBox(self.horizontalLayoutWidget_81)
        self.dendrogram.setObjectName("dendrogram")
        self.horizontalLayout_106.addWidget(self.dendrogram)
        self.horizontalLayoutWidget_87 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_87.setGeometry(QtCore.QRect(870, 220, 91, 31))
        self.horizontalLayoutWidget_87.setObjectName("horizontalLayoutWidget_87")
        self.horizontalLayout_112 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_87)
        self.horizontalLayout_112.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_112.setObjectName("horizontalLayout_112")
        self.writeFit = QtWidgets.QComboBox(self.horizontalLayoutWidget_87)
        self.writeFit.setObjectName("writeFit")
        self.horizontalLayout_112.addWidget(self.writeFit)
        self.horizontalLayoutWidget_86 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_86.setGeometry(QtCore.QRect(810, 200, 31, 21))
        self.horizontalLayoutWidget_86.setObjectName("horizontalLayoutWidget_86")
        self.horizontalLayout_111 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_86)
        self.horizontalLayout_111.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_111.setObjectName("horizontalLayout_111")
        self.label_51 = QtWidgets.QLabel(self.horizontalLayoutWidget_86)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_111.addWidget(self.label_51)
        self.horizontalLayoutWidget_84 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_84.setGeometry(QtCore.QRect(810, 270, 51, 31))
        self.horizontalLayoutWidget_84.setObjectName("horizontalLayoutWidget_84")
        self.horizontalLayout_109 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_84)
        self.horizontalLayout_109.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_109.setObjectName("horizontalLayout_109")
        self.label_49 = QtWidgets.QLabel(self.horizontalLayoutWidget_84)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_109.addWidget(self.label_49)
        self.horizontalLayoutWidget_89 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_89.setGeometry(QtCore.QRect(0, 330, 1001, 31))
        self.horizontalLayoutWidget_89.setObjectName("horizontalLayoutWidget_89")
        self.horizontalLayout_114 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_89)
        self.horizontalLayout_114.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_114.setObjectName("horizontalLayout_114")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_114.addItem(spacerItem8)
        self.alignBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_89)
        self.alignBut.setObjectName("alignBut")
        self.horizontalLayout_114.addWidget(self.alignBut)
        self.ali_remove_file = QtWidgets.QPushButton(self.horizontalLayoutWidget_89)
        self.ali_remove_file.setObjectName("ali_remove_file")
        self.horizontalLayout_114.addWidget(self.ali_remove_file)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_114.addItem(spacerItem9)
        self.horizontalLayoutWidget_90 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_90.setGeometry(QtCore.QRect(0, 310, 1001, 22))
        self.horizontalLayoutWidget_90.setObjectName("horizontalLayoutWidget_90")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_90)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.msgLabel2 = QtWidgets.QLabel(self.horizontalLayoutWidget_90)
        self.msgLabel2.setText("")
        self.msgLabel2.setObjectName("msgLabel2")
        self.horizontalLayout_14.addWidget(self.msgLabel2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.prepare_toolBox.addItem(self.page_2, "")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, 430, 981, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")

        self.retranslateUi(Form)
        self.prepare_toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.segToLabel.setText(_translate("Form", "To:"))
        self.label_7.setText(_translate("Form", "Patch terminal residue:"))
        self.segFromLabel.setText(_translate("Form", "Segment from:"))
        self.label_2.setText(_translate("Form", "Segment of residues:"))
        self.label_4.setText(_translate("Form", "Remove HETATM:"))
        self.repairBut.setText(_translate("Form", "Repair"))
        self.rep_remove_file.setText(_translate("Form", "Remove"))
        self.label.setText(_translate("Form", "Renumber residues:"))
        self.label_3.setText(_translate("Form", "Add patch:"))
        self.label_10.setText(_translate("Form", "Patch type:"))
        self.addBut.setText(_translate("Form", "Add"))
        self.minBut.setText(_translate("Form", "Delete"))
        self.searchRes.setPlaceholderText(_translate("Form", "Residue . . ."))
        self.label_11.setText(_translate("Form", "Chains:"))
        self.prepare_toolBox.setItemText(self.prepare_toolBox.indexOf(self.page), _translate("Form", "Repair Missing Atom"))
        self.alignAddBut.setText(_translate("Form", "Add"))
        self.alignMinBut.setText(_translate("Form", "Delete"))
        self.label_5.setText(_translate("Form", "Alignment type:"))
        self.label_8.setText(_translate("Form", "Local alignment:"))
        self.label_15.setText(_translate("Form", "Matrix:"))
        self.label_16.setText(_translate("Form", "Gap function:"))
        self.label_17.setText(_translate("Form", "1D gap open:"))
        self.label_18.setText(_translate("Form", "1D gap extension:"))
        self.label_20.setText(_translate("Form", "2D helix gap penalty:"))
        self.label_21.setText(_translate("Form", "2D beta gap penalty:"))
        self.label_22.setText(_translate("Form", "2D Accessibility gap penalty:"))
        self.label_23.setText(_translate("Form", "2D Straightness gap penalty:"))
        self.label_25.setText(_translate("Form", "2D CA-CA distance factor gap penalty:"))
        self.label_26.setText(_translate("Form", "2D DST min gap penalty:"))
        self.label_28.setText(_translate("Form", "2D DST power gap penalty:"))
        self.label_29.setText(_translate("Form", "2D structure profile gap penalty:"))
        self.label_31.setText(_translate("Form", "3D gap open:"))
        self.label_30.setText(_translate("Form", "3D gap extension:"))
        self.label_32.setText(_translate("Form", "Gap-gap score:"))
        self.label_33.setText(_translate("Form", "Overhang:"))
        self.label_34.setText(_translate("Form", "Max gap length:"))
        self.label_35.setText(_translate("Form", "Gap-residue score:"))
        self.autoOverHangLimlabel.setText(_translate("Form", "Auto overhang limit:"))
        self.label_39.setText(_translate("Form", "Auto overhang:"))
        self.overHangFaclabel.setText(_translate("Form", "Overhang factor:"))
        self.label_37.setText(_translate("Form", "Similarity flag:"))
        self.userMatrix.setText(_translate("Form", "Browse"))
        self.label_46.setText(_translate("Form", "User matrix:"))
        self.userMatrixTypelabel.setText(_translate("Form", "Matrix type:"))
        self.matrixOffsetlabel.setText(_translate("Form", "Matrix offset:"))
        self.label_45.setText(_translate("Form", "RMS cut off:"))
        self.label_48.setText(_translate("Form", "Dendrogram:"))
        self.label_50.setText(_translate("Form", "Write fit file:"))
        self.label_51.setText(_translate("Form", "Use fit:"))
        self.label_49.setText(_translate("Form", "Sequence:"))
        self.alignBut.setText(_translate("Form", "Align"))
        self.ali_remove_file.setText(_translate("Form", "Remove"))
        self.prepare_toolBox.setItemText(self.prepare_toolBox.indexOf(self.page_2), _translate("Form", "Alignment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

