# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpl_search_temp.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1017, 350)
        Form.setMouseTracking(True)
        Form.setAutoFillBackground(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 961, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_main.setContentsMargins(0, 0, 0, 0)
        self.layout_main.setObjectName("layout_main")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_125 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_125.setGeometry(QtCore.QRect(10, 300, 891, 31))
        self.horizontalLayoutWidget_125.setObjectName("horizontalLayoutWidget_125")
        self.horizontalLayout_212 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_125)
        self.horizontalLayout_212.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_212.setObjectName("horizontalLayout_212")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_212.addItem(spacerItem)
        self.searchBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_125)
        self.searchBut.setObjectName("searchBut")
        self.horizontalLayout_212.addWidget(self.searchBut)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_212.addItem(spacerItem1)
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(10, 190, 141, 21))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.blastParam = QtWidgets.QComboBox(self.horizontalLayoutWidget_18)
        self.blastParam.setObjectName("blastParam")
        self.horizontalLayout_19.addWidget(self.blastParam)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 170, 951, 21))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_17)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_18.addWidget(self.groupBox_2)
        self.horizontalLayoutWidget_91 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_91.setGeometry(QtCore.QRect(10, 280, 891, 31))
        self.horizontalLayoutWidget_91.setObjectName("horizontalLayoutWidget_91")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_91)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.msgLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_91)
        self.msgLabel.setText("")
        self.msgLabel.setObjectName("msgLabel")
        self.horizontalLayout_17.addWidget(self.msgLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 561, 131))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label.setStatusTip("")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.seq = QtWidgets.QTextEdit(self.gridLayoutWidget_6)
        self.seq.setObjectName("seq")
        self.gridLayout_6.addWidget(self.seq, 0, 1, 1, 1)
        self.browsSeq = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.browsSeq.setObjectName("browsSeq")
        self.gridLayout_6.addWidget(self.browsSeq, 1, 1, 1, 1)
        self.accession = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.accession.setObjectName("accession")
        self.gridLayout_6.addWidget(self.accession, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(590, 20, 160, 91))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.blastType = QtWidgets.QListWidget(self.gridLayoutWidget_7)
        self.blastType.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.blastType.setObjectName("blastType")
        self.gridLayout_8.addWidget(self.blastType, 0, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(770, 20, 181, 93))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.expectLabel = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.expectLabel.setEnabled(False)
        self.expectLabel.setObjectName("expectLabel")
        self.gridLayout_9.addWidget(self.expectLabel, 2, 0, 1, 1)
        self.searchType = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.searchType.setObjectName("searchType")
        self.gridLayout_9.addWidget(self.searchType, 0, 1, 1, 1)
        self.residuerangeLabel = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.residuerangeLabel.setEnabled(False)
        self.residuerangeLabel.setObjectName("residuerangeLabel")
        self.gridLayout_9.addWidget(self.residuerangeLabel, 1, 0, 1, 1)
        self.expect = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.expect.setEnabled(False)
        self.expect.setObjectName("expect")
        self.gridLayout_9.addWidget(self.expect, 2, 1, 1, 1)
        self.residueRange = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.residueRange.setEnabled(False)
        self.residueRange.setObjectName("residueRange")
        self.gridLayout_9.addWidget(self.residueRange, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 3, 0, 1, 1)
        self.title = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.title.setMouseTracking(False)
        self.title.setObjectName("title")
        self.gridLayout_9.addWidget(self.title, 3, 1, 1, 1)
        self.layout_main.addWidget(self.groupBox)
        self.horizontalLayoutWidget_39 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_39.setGeometry(QtCore.QRect(20, 230, 951, 61))
        self.horizontalLayoutWidget_39.setObjectName("horizontalLayoutWidget_39")
        self.layout_NCBI = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_39)
        self.layout_NCBI.setContentsMargins(0, 0, 0, 0)
        self.layout_NCBI.setObjectName("layout_NCBI")
        self.group_NCBI = QtWidgets.QGroupBox(self.horizontalLayoutWidget_39)
        self.group_NCBI.setEnabled(True)
        self.group_NCBI.setAutoFillBackground(False)
        self.group_NCBI.setStyleSheet("#group_NCBI {\n"
"    border: 0px solid gray;\n"
"}")
        self.group_NCBI.setTitle("")
        self.group_NCBI.setCheckable(False)
        self.group_NCBI.setObjectName("group_NCBI")
        self.gridLayoutWidget = QtWidgets.QWidget(self.group_NCBI)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 941, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.FilterNCBILabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.FilterNCBILabel.setObjectName("FilterNCBILabel")
        self.gridLayout.addWidget(self.FilterNCBILabel, 0, 2, 1, 1)
        self.matrixTypesNCBI = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.matrixTypesNCBI.setObjectName("matrixTypesNCBI")
        self.gridLayout.addWidget(self.matrixTypesNCBI, 0, 1, 1, 1)
        self.dropNCBI = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.dropNCBI.setObjectName("dropNCBI")
        self.gridLayout.addWidget(self.dropNCBI, 1, 7, 1, 1)
        self.alignNCBILabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.alignNCBILabel.setObjectName("alignNCBILabel")
        self.gridLayout.addWidget(self.alignNCBILabel, 0, 8, 1, 1)
        self.dropNCBILabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dropNCBILabel.setObjectName("dropNCBILabel")
        self.gridLayout.addWidget(self.dropNCBILabel, 1, 6, 1, 1)
        self.recNCBILabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.recNCBILabel.setObjectName("recNCBILabel")
        self.gridLayout.addWidget(self.recNCBILabel, 1, 2, 1, 1)
        self.gapOpenNCBILabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.gapOpenNCBILabel.setObjectName("gapOpenNCBILabel")
        self.gridLayout.addWidget(self.gapOpenNCBILabel, 0, 4, 1, 1)
        self.filterNCBI = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.filterNCBI.setObjectName("filterNCBI")
        self.gridLayout.addWidget(self.filterNCBI, 0, 3, 1, 1)
        self.gapOpenNCBI = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.gapOpenNCBI.setObjectName("gapOpenNCBI")
        self.gridLayout.addWidget(self.gapOpenNCBI, 0, 5, 1, 1)
        self.recordsNCBI = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.recordsNCBI.setObjectName("recordsNCBI")
        self.gridLayout.addWidget(self.recordsNCBI, 1, 3, 1, 1)
        self.gapExtNCBILabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.gapExtNCBILabel.setObjectName("gapExtNCBILabel")
        self.gridLayout.addWidget(self.gapExtNCBILabel, 1, 4, 1, 1)
        self.gapalignLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.gapalignLabel_2.setObjectName("gapalignLabel_2")
        self.gridLayout.addWidget(self.gapalignLabel_2, 0, 6, 1, 1)
        self.gapAlign = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.gapAlign.setObjectName("gapAlign")
        self.gridLayout.addWidget(self.gapAlign, 0, 7, 1, 1)
        self.gapExtNCBI = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.gapExtNCBI.setObjectName("gapExtNCBI")
        self.gridLayout.addWidget(self.gapExtNCBI, 1, 5, 1, 1)
        self.expectNCBiLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.expectNCBiLabel.setObjectName("expectNCBiLabel")
        self.gridLayout.addWidget(self.expectNCBiLabel, 0, 0, 1, 1)
        self.expectNCBI = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.expectNCBI.setObjectName("expectNCBI")
        self.gridLayout.addWidget(self.expectNCBI, 1, 1, 1, 1)
        self.expectNCBiLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.expectNCBiLabel_2.setObjectName("expectNCBiLabel_2")
        self.gridLayout.addWidget(self.expectNCBiLabel_2, 1, 0, 1, 1)
        self.alignmentsNCBI = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.alignmentsNCBI.setObjectName("alignmentsNCBI")
        self.gridLayout.addWidget(self.alignmentsNCBI, 0, 9, 1, 1)
        self.compositLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.compositLabel.setObjectName("compositLabel")
        self.gridLayout.addWidget(self.compositLabel, 1, 8, 1, 1)
        self.composit = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.composit.setObjectName("composit")
        self.gridLayout.addWidget(self.composit, 1, 9, 1, 1)
        self.layout_NCBI.addWidget(self.group_NCBI)
        self.horizontalLayoutWidget_92 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_92.setGeometry(QtCore.QRect(20, 230, 951, 61))
        self.horizontalLayoutWidget_92.setObjectName("horizontalLayoutWidget_92")
        self.layout_FASTM = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_92)
        self.layout_FASTM.setContentsMargins(0, 0, 0, 0)
        self.layout_FASTM.setObjectName("layout_FASTM")
        self.group_FASTM = QtWidgets.QGroupBox(self.horizontalLayoutWidget_92)
        self.group_FASTM.setStyleSheet("#group_FASTM {\n"
"    border: 0px solid gray;\n"
"}")
        self.group_FASTM.setTitle("")
        self.group_FASTM.setObjectName("group_FASTM")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.group_FASTM)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 941, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gapOpenFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.gapOpenFASTM.setObjectName("gapOpenFASTM")
        self.gridLayout_3.addWidget(self.gapOpenFASTM, 0, 7, 1, 1)
        self.filterFASTMLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.filterFASTMLabel.setObjectName("filterFASTMLabel")
        self.gridLayout_3.addWidget(self.filterFASTMLabel, 1, 2, 1, 1)
        self.recFASTMLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.recFASTMLabel.setObjectName("recFASTMLabel")
        self.gridLayout_3.addWidget(self.recFASTMLabel, 0, 4, 1, 1)
        self.filterFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.filterFASTM.setObjectName("filterFASTM")
        self.gridLayout_3.addWidget(self.filterFASTM, 1, 3, 1, 1)
        self.expectUpFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.expectUpFASTM.setObjectName("expectUpFASTM")
        self.gridLayout_3.addWidget(self.expectUpFASTM, 0, 3, 1, 1)
        self.statEstFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.statEstFASTM.setObjectName("statEstFASTM")
        self.gridLayout_3.addWidget(self.statEstFASTM, 1, 5, 1, 1)
        self.alignFASTMLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.alignFASTMLabel.setObjectName("alignFASTMLabel")
        self.gridLayout_3.addWidget(self.alignFASTMLabel, 0, 10, 1, 1)
        self.gapOpenFASTMLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.gapOpenFASTMLabel.setObjectName("gapOpenFASTMLabel")
        self.gridLayout_3.addWidget(self.gapOpenFASTMLabel, 0, 6, 1, 1)
        self.expectFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.expectFASTM.setObjectName("expectFASTM")
        self.gridLayout_3.addWidget(self.expectFASTM, 1, 1, 1, 1)
        self.matrixTypesFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.matrixTypesFASTM.setObjectName("matrixTypesFASTM")
        self.gridLayout_3.addWidget(self.matrixTypesFASTM, 0, 1, 1, 1)
        self.matrixFASTMLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.matrixFASTMLabel.setObjectName("matrixFASTMLabel")
        self.gridLayout_3.addWidget(self.matrixFASTMLabel, 0, 0, 1, 1)
        self.expectUpLabelFASTM = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.expectUpLabelFASTM.setObjectName("expectUpLabelFASTM")
        self.gridLayout_3.addWidget(self.expectUpLabelFASTM, 0, 2, 1, 1)
        self.expectFASTMLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.expectFASTMLabel.setObjectName("expectFASTMLabel")
        self.gridLayout_3.addWidget(self.expectFASTMLabel, 1, 0, 1, 1)
        self.recordsFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.recordsFASTM.setObjectName("recordsFASTM")
        self.gridLayout_3.addWidget(self.recordsFASTM, 0, 5, 1, 1)
        self.gapExtFASTMLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.gapExtFASTMLabel.setObjectName("gapExtFASTMLabel")
        self.gridLayout_3.addWidget(self.gapExtFASTMLabel, 1, 6, 1, 1)
        self.statLabelFASTM = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.statLabelFASTM.setObjectName("statLabelFASTM")
        self.gridLayout_3.addWidget(self.statLabelFASTM, 1, 4, 1, 1)
        self.gapExtFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.gapExtFASTM.setObjectName("gapExtFASTM")
        self.gridLayout_3.addWidget(self.gapExtFASTM, 1, 7, 1, 1)
        self.progLabelFASTM = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.progLabelFASTM.setObjectName("progLabelFASTM")
        self.gridLayout_3.addWidget(self.progLabelFASTM, 0, 8, 1, 1)
        self.progTypesFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.progTypesFASTM.setObjectName("progTypesFASTM")
        self.gridLayout_3.addWidget(self.progTypesFASTM, 0, 9, 1, 1)
        self.ktupLabelFASTM = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.ktupLabelFASTM.setObjectName("ktupLabelFASTM")
        self.gridLayout_3.addWidget(self.ktupLabelFASTM, 1, 8, 1, 1)
        self.ktupFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.ktupFASTM.setObjectName("ktupFASTM")
        self.gridLayout_3.addWidget(self.ktupFASTM, 1, 9, 1, 1)
        self.alignmentsFASTM = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.alignmentsFASTM.setObjectName("alignmentsFASTM")
        self.gridLayout_3.addWidget(self.alignmentsFASTM, 0, 11, 1, 1)
        self.layout_FASTM.addWidget(self.group_FASTM)
        self.horizontalLayoutWidget_69 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_69.setGeometry(QtCore.QRect(20, 230, 951, 61))
        self.horizontalLayoutWidget_69.setObjectName("horizontalLayoutWidget_69")
        self.layout_PSI_BLAST = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_69)
        self.layout_PSI_BLAST.setContentsMargins(0, 0, 0, 0)
        self.layout_PSI_BLAST.setObjectName("layout_PSI_BLAST")
        self.group_PSI_BLAST = QtWidgets.QGroupBox(self.horizontalLayoutWidget_69)
        self.group_PSI_BLAST.setStyleSheet("#group_PSI_BLAST {\n"
"    border: 0px solid gray;\n"
"}")
        self.group_PSI_BLAST.setTitle("")
        self.group_PSI_BLAST.setObjectName("group_PSI_BLAST")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.group_PSI_BLAST)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 941, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pssmPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.pssmPSIBLLabel.setObjectName("pssmPSIBLLabel")
        self.gridLayout_4.addWidget(self.pssmPSIBLLabel, 0, 0, 1, 1)
        self.pssmPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.pssmPSIBL.setObjectName("pssmPSIBL")
        self.gridLayout_4.addWidget(self.pssmPSIBL, 0, 1, 1, 1)
        self.matrixPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.matrixPSIBLLabel.setObjectName("matrixPSIBLLabel")
        self.gridLayout_4.addWidget(self.matrixPSIBLLabel, 1, 0, 1, 1)
        self.matrixTypesPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.matrixTypesPSIBL.setObjectName("matrixTypesPSIBL")
        self.gridLayout_4.addWidget(self.matrixTypesPSIBL, 1, 1, 1, 1)
        self.filterPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.filterPSIBLLabel.setObjectName("filterPSIBLLabel")
        self.gridLayout_4.addWidget(self.filterPSIBLLabel, 1, 2, 1, 1)
        self.expectPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.expectPSIBL.setObjectName("expectPSIBL")
        self.gridLayout_4.addWidget(self.expectPSIBL, 0, 3, 1, 1)
        self.recPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.recPSIBLLabel.setObjectName("recPSIBLLabel")
        self.gridLayout_4.addWidget(self.recPSIBLLabel, 0, 4, 1, 1)
        self.filterPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.filterPSIBL.setObjectName("filterPSIBL")
        self.gridLayout_4.addWidget(self.filterPSIBL, 1, 3, 1, 1)
        self.recordsPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.recordsPSIBL.setObjectName("recordsPSIBL")
        self.gridLayout_4.addWidget(self.recordsPSIBL, 0, 5, 1, 1)
        self.expectPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.expectPSIBLLabel.setObjectName("expectPSIBLLabel")
        self.gridLayout_4.addWidget(self.expectPSIBLLabel, 0, 2, 1, 1)
        self.dropPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.dropPSIBLLabel.setObjectName("dropPSIBLLabel")
        self.gridLayout_4.addWidget(self.dropPSIBLLabel, 1, 4, 1, 1)
        self.dropPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.dropPSIBL.setObjectName("dropPSIBL")
        self.gridLayout_4.addWidget(self.dropPSIBL, 1, 5, 1, 1)
        self.fdrop = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.fdrop.setObjectName("fdrop")
        self.gridLayout_4.addWidget(self.fdrop, 0, 7, 1, 1)
        self.gapOpenPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.gapOpenPSIBLLabel.setObjectName("gapOpenPSIBLLabel")
        self.gridLayout_4.addWidget(self.gapOpenPSIBLLabel, 1, 6, 1, 1)
        self.gapExtPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.gapExtPSIBLLabel.setObjectName("gapExtPSIBLLabel")
        self.gridLayout_4.addWidget(self.gapExtPSIBLLabel, 0, 8, 1, 1)
        self.fdropLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.fdropLabel.setObjectName("fdropLabel")
        self.gridLayout_4.addWidget(self.fdropLabel, 0, 6, 1, 1)
        self.gapOpenPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.gapOpenPSIBL.setObjectName("gapOpenPSIBL")
        self.gridLayout_4.addWidget(self.gapOpenPSIBL, 1, 7, 1, 1)
        self.gapExtPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.gapExtPSIBL.setObjectName("gapExtPSIBL")
        self.gridLayout_4.addWidget(self.gapExtPSIBL, 0, 9, 1, 1)
        self.alignPSIBLLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.alignPSIBLLabel.setObjectName("alignPSIBLLabel")
        self.gridLayout_4.addWidget(self.alignPSIBLLabel, 1, 8, 1, 1)
        self.alignmentsPSIBL = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.alignmentsPSIBL.setObjectName("alignmentsPSIBL")
        self.gridLayout_4.addWidget(self.alignmentsPSIBL, 1, 9, 1, 1)
        self.layout_PSI_BLAST.addWidget(self.group_PSI_BLAST)
        self.horizontalLayoutWidget_88 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_88.setGeometry(QtCore.QRect(20, 230, 951, 61))
        self.horizontalLayoutWidget_88.setObjectName("horizontalLayoutWidget_88")
        self.layout_PSI_search = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_88)
        self.layout_PSI_search.setContentsMargins(0, 0, 0, 0)
        self.layout_PSI_search.setObjectName("layout_PSI_search")
        self.group_PSI_search = QtWidgets.QGroupBox(self.horizontalLayoutWidget_88)
        self.group_PSI_search.setStyleSheet("#group_PSI_search {\n"
"    border: 0px solid gray;\n"
"}")
        self.group_PSI_search.setTitle("")
        self.group_PSI_search.setObjectName("group_PSI_search")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.group_PSI_search)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 941, 51))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pssmPSISELabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.pssmPSISELabel.setObjectName("pssmPSISELabel")
        self.gridLayout_5.addWidget(self.pssmPSISELabel, 0, 0, 1, 1)
        self.matrixPSISELabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.matrixPSISELabel.setObjectName("matrixPSISELabel")
        self.gridLayout_5.addWidget(self.matrixPSISELabel, 1, 0, 1, 1)
        self.pssmPSISE = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.pssmPSISE.setObjectName("pssmPSISE")
        self.gridLayout_5.addWidget(self.pssmPSISE, 0, 1, 1, 1)
        self.alignPSISELabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.alignPSISELabel.setObjectName("alignPSISELabel")
        self.gridLayout_5.addWidget(self.alignPSISELabel, 1, 4, 1, 1)
        self.filterPSISE = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.filterPSISE.setObjectName("filterPSISE")
        self.gridLayout_5.addWidget(self.filterPSISE, 1, 3, 1, 1)
        self.alignmentsPSISE = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.alignmentsPSISE.setObjectName("alignmentsPSISE")
        self.gridLayout_5.addWidget(self.alignmentsPSISE, 1, 5, 1, 1)
        self.expectPSISE = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.expectPSISE.setObjectName("expectPSISE")
        self.gridLayout_5.addWidget(self.expectPSISE, 0, 3, 1, 1)
        self.filterPSISELabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.filterPSISELabel.setObjectName("filterPSISELabel")
        self.gridLayout_5.addWidget(self.filterPSISELabel, 1, 2, 1, 1)
        self.recordsPSISE = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.recordsPSISE.setObjectName("recordsPSISE")
        self.gridLayout_5.addWidget(self.recordsPSISE, 0, 5, 1, 1)
        self.gapOpenPSISELabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gapOpenPSISELabel.setObjectName("gapOpenPSISELabel")
        self.gridLayout_5.addWidget(self.gapOpenPSISELabel, 0, 6, 1, 1)
        self.expectPSISELabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.expectPSISELabel.setObjectName("expectPSISELabel")
        self.gridLayout_5.addWidget(self.expectPSISELabel, 0, 2, 1, 1)
        self.matrixTypesPSISE = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.matrixTypesPSISE.setObjectName("matrixTypesPSISE")
        self.gridLayout_5.addWidget(self.matrixTypesPSISE, 1, 1, 1, 1)
        self.gapOpenPSISE = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.gapOpenPSISE.setObjectName("gapOpenPSISE")
        self.gridLayout_5.addWidget(self.gapOpenPSISE, 0, 7, 1, 1)
        self.gapExtPSISELabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gapExtPSISELabel.setObjectName("gapExtPSISELabel")
        self.gridLayout_5.addWidget(self.gapExtPSISELabel, 1, 6, 1, 1)
        self.gapExtPSISE_3 = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.gapExtPSISE_3.setObjectName("gapExtPSISE_3")
        self.gridLayout_5.addWidget(self.gapExtPSISE_3, 1, 7, 1, 1)
        self.recPSISELabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.recPSISELabel.setObjectName("recPSISELabel")
        self.gridLayout_5.addWidget(self.recPSISELabel, 0, 4, 1, 1)
        self.layout_PSI_search.addWidget(self.group_PSI_search)
        self.horizontalLayoutWidget_40 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_40.setGeometry(QtCore.QRect(20, 230, 951, 61))
        self.horizontalLayoutWidget_40.setObjectName("horizontalLayoutWidget_40")
        self.layout_FASTA = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_40)
        self.layout_FASTA.setContentsMargins(0, 0, 0, 0)
        self.layout_FASTA.setObjectName("layout_FASTA")
        self.group_FASTA = QtWidgets.QGroupBox(self.horizontalLayoutWidget_40)
        self.group_FASTA.setStyleSheet("#group_FASTA {\n"
"    border: 0px solid gray;\n"
"}")
        self.group_FASTA.setTitle("")
        self.group_FASTA.setObjectName("group_FASTA")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.group_FASTA)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 941, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ktup = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.ktup.setObjectName("ktup")
        self.gridLayout_2.addWidget(self.ktup, 1, 9, 1, 1)
        self.alignmentsFASTA = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.alignmentsFASTA.setObjectName("alignmentsFASTA")
        self.gridLayout_2.addWidget(self.alignmentsFASTA, 0, 11, 1, 1)
        self.matrixFASTALabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.matrixFASTALabel.setObjectName("matrixFASTALabel")
        self.gridLayout_2.addWidget(self.matrixFASTALabel, 0, 0, 1, 1)
        self.expectFASTA = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.expectFASTA.setObjectName("expectFASTA")
        self.gridLayout_2.addWidget(self.expectFASTA, 1, 1, 1, 1)
        self.ktupLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ktupLabel.setObjectName("ktupLabel")
        self.gridLayout_2.addWidget(self.ktupLabel, 1, 8, 1, 1)
        self.progTypes = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.progTypes.setObjectName("progTypes")
        self.gridLayout_2.addWidget(self.progTypes, 0, 9, 1, 1)
        self.gapOpenFASTALabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.gapOpenFASTALabel.setObjectName("gapOpenFASTALabel")
        self.gridLayout_2.addWidget(self.gapOpenFASTALabel, 0, 6, 1, 1)
        self.filterFASTA = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.filterFASTA.setObjectName("filterFASTA")
        self.gridLayout_2.addWidget(self.filterFASTA, 1, 3, 1, 1)
        self.progLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.progLabel.setObjectName("progLabel")
        self.gridLayout_2.addWidget(self.progLabel, 0, 8, 1, 1)
        self.expectUp = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.expectUp.setObjectName("expectUp")
        self.gridLayout_2.addWidget(self.expectUp, 0, 3, 1, 1)
        self.gapOpenFASTA = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.gapOpenFASTA.setObjectName("gapOpenFASTA")
        self.gridLayout_2.addWidget(self.gapOpenFASTA, 0, 7, 1, 1)
        self.filterFASTALabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.filterFASTALabel.setObjectName("filterFASTALabel")
        self.gridLayout_2.addWidget(self.filterFASTALabel, 1, 2, 1, 1)
        self.gapExtFASTALabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.gapExtFASTALabel.setObjectName("gapExtFASTALabel")
        self.gridLayout_2.addWidget(self.gapExtFASTALabel, 1, 6, 1, 1)
        self.matrixTypesFASTA = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.matrixTypesFASTA.setObjectName("matrixTypesFASTA")
        self.gridLayout_2.addWidget(self.matrixTypesFASTA, 0, 1, 1, 1)
        self.alignFASTALabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.alignFASTALabel.setObjectName("alignFASTALabel")
        self.gridLayout_2.addWidget(self.alignFASTALabel, 0, 10, 1, 1)
        self.recordsFASTA = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.recordsFASTA.setObjectName("recordsFASTA")
        self.gridLayout_2.addWidget(self.recordsFASTA, 0, 5, 1, 1)
        self.recFASTALabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.recFASTALabel.setObjectName("recFASTALabel")
        self.gridLayout_2.addWidget(self.recFASTALabel, 0, 4, 1, 1)
        self.statEst = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.statEst.setObjectName("statEst")
        self.gridLayout_2.addWidget(self.statEst, 1, 5, 1, 1)
        self.expectUpLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.expectUpLabel.setObjectName("expectUpLabel")
        self.gridLayout_2.addWidget(self.expectUpLabel, 0, 2, 1, 1)
        self.expectFASTALabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.expectFASTALabel.setObjectName("expectFASTALabel")
        self.gridLayout_2.addWidget(self.expectFASTALabel, 1, 0, 1, 1)
        self.statLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.statLabel.setObjectName("statLabel")
        self.gridLayout_2.addWidget(self.statLabel, 1, 4, 1, 1)
        self.gapExtFASTA = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.gapExtFASTA.setObjectName("gapExtFASTA")
        self.gridLayout_2.addWidget(self.gapExtFASTA, 1, 7, 1, 1)
        self.layout_FASTA.addWidget(self.group_FASTA)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Search Template"))
        self.searchBut.setText(_translate("Form", "Search"))
        self.groupBox_2.setTitle(_translate("Form", "BLAST Parameters"))
        self.label.setToolTip(_translate("Form", "<html><head/><body><p>The target sequence must be longer than 30 residues.</p></body></html>"))
        self.label.setText(_translate("Form", "Enter Sequence:"))
        self.browsSeq.setText(_translate("Form", "Browse file"))
        self.accession.setPlaceholderText(_translate("Form", "Separate by space . . ."))
        self.label_3.setToolTip(_translate("Form", "<html><head/><body><p>UniProt, NCBI or PDB accession numbers.</p></body></html>"))
        self.label_3.setText(_translate("Form", "Accession number(s):"))
        self.label_4.setToolTip(_translate("Form", "<html><head/><body><p>The BLAST program to be used for the Sequence Similarity Search.</p></body></html>"))
        self.label_4.setText(_translate("Form", "BLAST type:"))
        self.expectLabel.setToolTip(_translate("Form", "<html><head/><body><p>PfamScan expectation value cut-off. Default value is: 10.</p></body></html>"))
        self.expectLabel.setText(_translate("Form", "E value:"))
        self.residuerangeLabel.setText(_translate("Form", "Residue ranges:"))
        self.residueRange.setPlaceholderText(_translate("Form", "e.g. 7-100, 125-300, ..."))
        self.label_5.setText(_translate("Form", "Search by:"))
        self.label_8.setText(_translate("Form", "Title:"))
        self.FilterNCBILabel.setToolTip(_translate("Form", "<html><head/><body><p>Filter regions of low sequence complexity. This can avoid issues with low complexity sequences where matches are found due to composition rather than meaningful sequence similarity. However in some cases filtering also masks regions of interest and so should be used with caution.</p></body></html>"))
        self.FilterNCBILabel.setText(_translate("Form", "Filter:"))
        self.alignNCBILabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of match alignments reported in the result output.</p></body></html>"))
        self.alignNCBILabel.setText(_translate("Form", "Alignments:"))
        self.dropNCBILabel.setToolTip(_translate("Form", "<html><head/><body><p>The amount a score can drop before gapped extension of word hits is halted.</p></body></html>"))
        self.dropNCBILabel.setText(_translate("Form", "Dropoff:"))
        self.recNCBILabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of match score summaries reported in the result output.</p></body></html>"))
        self.recNCBILabel.setText(_translate("Form", "Scores:"))
        self.gapOpenNCBILabel.setToolTip(_translate("Form", "<html><head/><body><p>Score for the first residue in a gap.</p></body></html>"))
        self.gapOpenNCBILabel.setText(_translate("Form", "Gap open:"))
        self.gapExtNCBILabel.setToolTip(_translate("Form", "<html><head/><body><p>Score for each additional residue in a gap.</p></body></html>"))
        self.gapExtNCBILabel.setText(_translate("Form", "Gap extension:"))
        self.gapalignLabel_2.setToolTip(_translate("Form", "<html><head/><body><p>This tells the program the perform optimised alignments within regions involving gaps. If set to Yes, the program will perform an alignment using gaps. Otherwise, if it is set to No, it will report only individual HSP where two sequence match each other, and thus will not produce alignments with gaps.</p></body></html>"))
        self.gapalignLabel_2.setText(_translate("Form", "Gapalign:"))
        self.expectNCBiLabel.setToolTip(_translate("Form", "<html><head/><body><p>The substitution matrix used for scoring alignments when searching the database.</p></body></html>"))
        self.expectNCBiLabel.setText(_translate("Form", "Matrix:"))
        self.expectNCBiLabel_2.setToolTip(_translate("Form", "<html><head/><body><p>Limits the number of scores and alignments reported based on the expectation value. This is the maximum number of times the match is expected to occur by chance.</p></body></html>"))
        self.expectNCBiLabel_2.setText(_translate("Form", "Expectation value:"))
        self.compositLabel.setToolTip(_translate("Form", "<html><head/><body><p>Use composition-based statistics.</p></body></html>"))
        self.compositLabel.setText(_translate("Form", "Compositional based:"))
        self.filterFASTMLabel.setToolTip(_translate("Form", "<html><head/><body><p>Filter regions of low sequence complexity. This can avoid issues with low complexity sequences where matches are found due to composition rather then meaningful sequence similarity. However in some cases filtering also masks regions of interest and so should be used with caution.</p></body></html>"))
        self.filterFASTMLabel.setText(_translate("Form", "Filter:"))
        self.recFASTMLabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of match score summaries reported in the result output.</p></body></html>"))
        self.recFASTMLabel.setText(_translate("Form", "Scores:"))
        self.alignFASTMLabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of match score summaries reported in the result output.</p></body></html>"))
        self.alignFASTMLabel.setText(_translate("Form", "Alignments:"))
        self.gapOpenFASTMLabel.setToolTip(_translate("Form", "<html><head/><body><p>Score for the first residue in a gap.</p></body></html>"))
        self.gapOpenFASTMLabel.setText(_translate("Form", "Gap open:"))
        self.matrixFASTMLabel.setToolTip(_translate("Form", "<html><head/><body><p>The comparison matrix to be used to score alignments when searching the database.</p></body></html>"))
        self.matrixFASTMLabel.setText(_translate("Form", "Matrix:"))
        self.expectUpLabelFASTM.setToolTip(_translate("Form", "<html><head/><body><p>Limits the number of scores and alignments reported based on the expectation value. This is the maximum number of times the match is expected to occur by chance.</p></body></html>"))
        self.expectUpLabelFASTM.setText(_translate("Form", "Expectation Up lim:"))
        self.expectFASTMLabel.setToolTip(_translate("Form", "<html><head/><body><p>Limit the number of scores and alignments reported based on the expectation value. This is the minimum number of times the match is expected to occur by chance. This allows closely related matches to be excluded from the result in favor of more distant relationships.</p></body></html>"))
        self.expectFASTMLabel.setText(_translate("Form", "Expectation value:"))
        self.gapExtFASTMLabel.setToolTip(_translate("Form", "<html><head/><body><p>Score for the first residue in a gap.</p></body></html>"))
        self.gapExtFASTMLabel.setText(_translate("Form", "Gap extension:"))
        self.statLabelFASTM.setToolTip(_translate("Form", "<html><head/><body><p>The statistical routines assume that the library contains a large sample of unrelated sequences. Options to select what method to use include regression, maximum likelihood estimates, shuffles, or combinations of these.</p></body></html>"))
        self.statLabelFASTM.setText(_translate("Form", "Statistical estimates:"))
        self.progLabelFASTM.setToolTip(_translate("Form", "<html><head/><body><p>The FASTA program to be used for the Sequence Similarity Search.</p></body></html>"))
        self.progLabelFASTM.setText(_translate("Form", "Program:"))
        self.ktupLabelFASTM.setToolTip(_translate("Form", "<html><head/><body><p>FASTA uses a rapid word-based lookup strategy to speed the initial phase of the similarity search. The KTUP is used to control the sensitivity of the search. Lower values lead to more sensitive, but slower searches.</p></body></html>"))
        self.ktupLabelFASTM.setText(_translate("Form", "KTUP:"))
        self.pssmPSIBLLabel.setToolTip(_translate("Form", "<html><head/><body><p>Expectation value threshold for automatic selection of matched sequences for inclusion in PSSM at each iteration.</p></body></html>"))
        self.pssmPSIBLLabel.setText(_translate("Form", "PSSM Ev cut-off:"))
        self.matrixPSIBLLabel.setToolTip(_translate("Form", "<html><head/><body><p>The substitution matrix used for scoring alignments when searching the database.</p></body></html>"))
        self.matrixPSIBLLabel.setText(_translate("Form", "Matrix:"))
        self.filterPSIBLLabel.setToolTip(_translate("Form", "<html><head/><body><p>Filter regions of low sequence complexity. This can avoid issues with low complexity sequences where matches are found due to composition rather than meaningful sequence similarity. However in some cases filtering also masks regions of interest and so should be used with caution.</p></body></html>"))
        self.filterPSIBLLabel.setText(_translate("Form", "Filter:"))
        self.recPSIBLLabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of match score summaries reported in the result output.</p></body></html>"))
        self.recPSIBLLabel.setText(_translate("Form", "Scores:"))
        self.expectPSIBLLabel.setToolTip(_translate("Form", "<html><head/><body><p>Limits the number of scores and alignments reported based on the expectation value. This is the maximum number of times the match is expected to occur by chance.</p></body></html>"))
        self.expectPSIBLLabel.setText(_translate("Form", "Expectation:"))
        self.dropPSIBLLabel.setToolTip(_translate("Form", "<html><head/><body><p>The amount a score can drop before extension of word hits is halted.</p></body></html>"))
        self.dropPSIBLLabel.setText(_translate("Form", "Dropoff:"))
        self.gapOpenPSIBLLabel.setToolTip(_translate("Form", "<html><head/><body><p>Score for the first residue in a gap.</p></body></html>"))
        self.gapOpenPSIBLLabel.setText(_translate("Form", "Gap open:"))
        self.gapExtPSIBLLabel.setToolTip(_translate("Form", "<html><head/><body><p>Score for the first residue in a gap.</p></body></html>"))
        self.gapExtPSIBLLabel.setText(_translate("Form", "Gap extension:"))
        self.fdropLabel.setToolTip(_translate("Form", "<html><head/><body><p>Dropoff value for final gapped alignment.</p></body></html>"))
        self.fdropLabel.setText(_translate("Form", "Final dropoff:"))
        self.alignPSIBLLabel.setToolTip(_translate("Form", "Maximum number of match alignments reported in the result output."))
        self.alignPSIBLLabel.setText(_translate("Form", "Alignments:"))
        self.pssmPSISELabel.setToolTip(_translate("Form", "<html><head/><body><p>Expectation value threshold for automatic selection of matched sequences for inclusion in the PSSM at each iteration.</p></body></html>"))
        self.pssmPSISELabel.setText(_translate("Form", "PSSM Ev cut-off:"))
        self.matrixPSISELabel.setToolTip(_translate("Form", "<html><head/><body><p>The comparison matrix to be used to score alignments when searching the database.</p></body></html>"))
        self.matrixPSISELabel.setText(_translate("Form", "Matrix:"))
        self.alignPSISELabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of alignments reported in the result output.</p></body></html>"))
        self.alignPSISELabel.setText(_translate("Form", "Alignments:"))
        self.filterPSISELabel.setToolTip(_translate("Form", "<html><head/><body><p>Filter regions of low sequence complexity. This can avoid issues with low complexity sequences where matches are found due to composition rather then meaningful sequence similarity. However in some cases filtering also masks regions of interest and so should be used with caution.</p></body></html>"))
        self.filterPSISELabel.setText(_translate("Form", "Filter:"))
        self.gapOpenPSISELabel.setToolTip(_translate("Form", "<html><head/><body><p>Penalty taken away from the score when a gap is created in sequence. Increasing the gap opening penalty will decrease the number of gaps in the final alignment.</p></body></html>"))
        self.gapOpenPSISELabel.setText(_translate("Form", "Gap open:"))
        self.expectPSISELabel.setToolTip(_translate("Form", "<html><head/><body><p>Limits the number of scores and alignments reported based on the expectation value. This value is the maximum number of times the match is expected to occur by chance.</p></body></html>"))
        self.expectPSISELabel.setText(_translate("Form", "Expectation:"))
        self.gapExtPSISELabel.setToolTip(_translate("Form", "<html><head/><body><p>Penalty taken away from the score for each base or residue in the gap. Increasing the gap extension penalty favours short gaps in the final alignment, conversly, decreasing the gap extension penalty favours long gaps in the final alignment.</p></body></html>"))
        self.gapExtPSISELabel.setText(_translate("Form", "Gap extension:"))
        self.recPSISELabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of alignment score summaries reported in the result output.</p></body></html>"))
        self.recPSISELabel.setText(_translate("Form", "Scores:"))
        self.matrixFASTALabel.setToolTip(_translate("Form", "<html><head/><body><p>The substitution matrix used for scoring alignments when searching the database. Target identity is the average alignment identity the matrix would produce in the absence of homology and can be used to compare different matrix types. Alignment boundaries are more accurate when the alignment identity matches the target identity percentage.</p></body></html>"))
        self.matrixFASTALabel.setText(_translate("Form", "Matrix:"))
        self.ktupLabel.setToolTip(_translate("Form", "<html><head/><body><p>FASTA uses a rapid word-based lookup strategy to speed the initial phase of the similarity search. The KTUP is used to control the sensitivity of the search. Lower values lead to more sensitive, but slower searches.</p></body></html>"))
        self.ktupLabel.setText(_translate("Form", "KTUP:"))
        self.gapOpenFASTALabel.setToolTip(_translate("Form", "<html><head/><body><p>Score for the first residue in a gap.</p></body></html>"))
        self.gapOpenFASTALabel.setText(_translate("Form", "Gap open:"))
        self.progLabel.setToolTip(_translate("Form", "<html><head/><body><p>The FASTA program to be used for the Sequence Similarity Search.</p></body></html>"))
        self.progLabel.setText(_translate("Form", "Program:"))
        self.filterFASTALabel.setToolTip(_translate("Form", "<html><head/><body><p>Filter regions of low sequence complexity. This can avoid issues with low complexity sequences where matches are found due to composition rather then meaningful sequence similarity. However in some cases filtering also masks regions of interest and so should be used with caution.</p></body></html>"))
        self.filterFASTALabel.setText(_translate("Form", "Filter:"))
        self.gapExtFASTALabel.setToolTip(_translate("Form", "<html><head/><body><p>Score for each additional residue in a gap.</p></body></html>"))
        self.gapExtFASTALabel.setText(_translate("Form", "Gap extension:"))
        self.alignFASTALabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of match alignments reported in the result output.</p></body></html>"))
        self.alignFASTALabel.setText(_translate("Form", "Alignments:"))
        self.recFASTALabel.setToolTip(_translate("Form", "<html><head/><body><p>Maximum number of match score summaries reported in the result output.</p></body></html>"))
        self.recFASTALabel.setText(_translate("Form", "Scores:"))
        self.expectUpLabel.setToolTip(_translate("Form", "<html><head/><body><p>Limits the number of scores and alignments reported based on the expectation value. This is the maximum number of times the match is expected to occur by chance.</p></body></html>"))
        self.expectUpLabel.setText(_translate("Form", "Expectation Up lim:"))
        self.expectFASTALabel.setToolTip(_translate("Form", "<html><head/><body><p>Limit the number of scores and alignments reported based on the expectation value. This is the minimum number of times the match is expected to occur by chance. This allows closely related matches to be excluded from the result in favor of more distant relationships.</p></body></html>"))
        self.expectFASTALabel.setText(_translate("Form", "Expectation value:"))
        self.statLabel.setToolTip(_translate("Form", "<html><head/><body><p>The statistical routines assume that the library contains a large sample of unrelated sequences. Options to select what method to use include regression, maximum likelihood estimates, shuffles, or combinations of these.</p></body></html>"))
        self.statLabel.setText(_translate("Form", "Statistical estimates:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
