# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpl_select_temp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(976, 477)
        Form.setAutoFillBackground(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 961, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 340, 941, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.showBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.showBut.setObjectName("showBut")
        self.horizontalLayout_10.addWidget(self.showBut)
        self.downloadBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.downloadBut.setObjectName("downloadBut")
        self.horizontalLayout_10.addWidget(self.downloadBut)
        self.compareBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.compareBut.setObjectName("compareBut")
        self.horizontalLayout_10.addWidget(self.compareBut)
        self.viewBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.viewBut.setEnabled(True)
        self.viewBut.setObjectName("viewBut")
        self.horizontalLayout_10.addWidget(self.viewBut)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 80, 941, 211))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.template_table = QtWidgets.QTableView(self.horizontalLayoutWidget_5)
        self.template_table.setStyleSheet("")
        self.template_table.setProperty("showDropIndicator", False)
        self.template_table.setAlternatingRowColors(True)
        self.template_table.setShowGrid(False)
        self.template_table.setGridStyle(QtCore.Qt.SolidLine)
        self.template_table.setSortingEnabled(True)
        self.template_table.setObjectName("template_table")
        self.horizontalLayout_5.addWidget(self.template_table)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 290, 941, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pdb_selected = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.pdb_selected.setStyleSheet("")
        self.pdb_selected.setReadOnly(False)
        self.pdb_selected.setObjectName("pdb_selected")
        self.horizontalLayout_11.addWidget(self.pdb_selected)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(10, 323, 941, 22))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.msgLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.msgLabel.setText("")
        self.msgLabel.setObjectName("msgLabel")
        self.horizontalLayout_8.addWidget(self.msgLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 29, 571, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.programTypeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.programTypeLabel.setText("")
        self.programTypeLabel.setObjectName("programTypeLabel")
        self.gridLayout.addWidget(self.programTypeLabel, 1, 1, 1, 1)
        self.blastFile = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blastFile.sizePolicy().hasHeightForWidth())
        self.blastFile.setSizePolicy(sizePolicy)
        self.blastFile.setObjectName("blastFile")
        self.gridLayout.addWidget(self.blastFile, 0, 1, 1, 1)
        self.FBRec = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FBRec.sizePolicy().hasHeightForWidth())
        self.FBRec.setSizePolicy(sizePolicy)
        self.FBRec.setObjectName("FBRec")
        self.gridLayout.addWidget(self.FBRec, 0, 3, 1, 1)
        self.saveCSV = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.saveCSV.setObjectName("saveCSV")
        self.gridLayout.addWidget(self.saveCSV, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Select Template"))
        self.showBut.setText(_translate("Form", "Show templates"))
        self.downloadBut.setText(_translate("Form", "Download from RCSB"))
        self.compareBut.setText(_translate("Form", "Compare selected templates"))
        self.viewBut.setText(_translate("Form", "View comparing result"))
        self.pdb_selected.setPlaceholderText(_translate("Form", "Enter PDB codes . . ."))
        self.label.setText(_translate("Form", "File:"))
        self.label_2.setText(_translate("Form", "Records:"))
        self.label_3.setText(_translate("Form", "Program:"))
        self.FBRec.setText(_translate("Form", "10"))
        self.saveCSV.setText(_translate("Form", "Save as CSV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

